### ISSUE TITLE
rebuild resets playback position

### ISSUE THREAD

**Issue by claudeha** [3Dickulus/FragM#113]
**Describe the feature request**
When saving or otherwise triggering the rebuild of a frag, while animation playback is running, the time slider is reset to the last manually set position.  I can see that would be helpful when working on the code for a specific time-frame of a long animation, but it would also be nice to also have the option to keep the time free-running, for fluid live-coding performances or when working on a loop (two example use cases).

**To Reproduce**
1. Switch to animation mode
2. Set duration of time slider long enough to see the effects
3. Enable plackback
4. Rebuild the frag
5. See time slider reset to last manually set position, instead of continuing from where it was before the rebuild.

**Desired behavior**
For there to be a mode where time is continually advancing at a constant speed regardless of frag rebuilds.

**Desktop (please complete the following information):**
 - OS: Debian Buster

**Comment by 3Dickulus** [comment]
I believe this is legacy behaviour from 0.95 ??? just tried to compile the original and it fails to run the old QGLFBO does not work in 5.9

option = `continuous` or `reset to last manual position`  sounds like a good candidate.

**Comment by 3Dickulus** [comment]
...for VJing or live presentation?

**Comment by claudeha** [comment]
yeah that's one use-case!

**Comment by 3Dickulus** [comment]
I remind all, FragM is a GLSL development environment, use it to develop your special frags to be used with specialized render/playback software. If you want to VJ then use a VJ suite, if the VJ suite requires shader code then perhaps a few mods to FragM's internals for some compatibility to allow development of usable shader code for the VJ suite.

**Comment by 3Dickulus** [comment]
...on Rebuild all information about the frag is trashed, the entire VariableEditor interface is rebuilt because we have no idea, until rebuild, what viable uniforms exist in the frag or how many keyframes are still there... but still something to look at as a preferences option. Just track lastTime as currentTime every frame instead of on slider drag+release.
