### ISSUE TITLE
video textures

### ISSUE THREAD

**Issue by claudeha** [3Dickulus/FragM#118]
**Is your feature request related to a problem? Please describe.**

Would be cool to be able to do stuff where the time slider controls which frame of a video is uploaded to a `uniform sampler2D`.

**Describe the solution you'd like**

- option to load video files for sampler2D
- manual adjustment (or loop) of time slider does hard seek
- incremental playback of time slider decodes successive frames optimally (no hard seek, handles P and B frames nicely)
- (maybe) frame dropping if video decoding can't keep up with playback

**Describe alternatives you've considered**
- see other feature request about array textures (for short videos only)
- fqs scripts can set textures from image sequences, but that is not interactive

**Additional context**
- video frame number change should reuse a single texture object without requiring a rebuild of the frag

**Comment by 3Dickulus** [comment]
post compression images are not at all desirable so no, see other post

**Comment by claudeha** [comment]
There are lossless video formats (eg MKV or MOV with PNG frames).
