### ISSUE TITLE
webcam textures

### ISSUE THREAD

**Issue by claudeha** [3Dickulus/FragM#119]
**Is your feature request related to a problem? Please describe.**
Live webcam on a texture!

**Describe the solution you'd like**
- every frame the current webcam image is uploaded to the GPU.

**Describe alternatives you've considered**
- video textures but they aren't live (see #117 and #118)

**Additional context**
- breaks high resolution rendering
- should be easily able to replace webcam texture with video file texture for this reason

**Comment by 3Dickulus** [comment]
no, this would be a task best performed by specialized render/playback code, not a task for a development environment

**Comment by claudeha** [comment]
Sure, this one was a bit of a wild idea :)
