### ISSUE TITLE
animation rendering framerate issue (repeated frames)

### ISSUE THREAD

**Issue by claudeha** [3Dickulus/FragM#12]
When trying to render an animation at 60fps instead of the default 25fps I get repeated frames:

    AAADDFFFII...

instead of what I expect:

    ABCDEFGHIJ...

Not had time to debug this yet.

A workaround for now is to have `float time2 = time * 25.0 / 60.0;` and use `time2` instead of `time`, rendering the correct frame count but selecting 25fps in the render dialog.

**Comment by 3Dickulus** [comment]
I just did a 2 second 60fps test with the "Simple keyframe animation" frag from Examples. it rendered all frames in sequence 1 at a time as expected, no doubles or triples or skipping.

Try going to Edit->Preferences and set "OpenGL refresh rate" to 16ms and "Animation frame rate" to 60fps

This is what I did before rendering and it seems to work, I assume you are using the latest sources and compiling yourself?

Where is `float time2 = time * 25.0 / 60.0;` in GLSL or C++ ?

**Comment by claudeha** [comment]
Oh, I didn't know about the Edit->Preferences, I just set the frame rate in the Render dialog.  Will try once my current render is completed (~30mins from now).

I set the `time2` in the main GLSL frag file at top level scope, just after `uniform float time;`.

**Comment by 3Dickulus** [comment]
The preferences setting should have priority and the framerate in the animation dialog will be set automatically, maybe should make the change in the animation dialog record the change to preferences settings.

**Comment by claudeha** [comment]
Or make the animation dialog read-only with a note to see prefs to change it?

Anyway setting it in Edit->Preferences worked, got an animation without repeats.  Thanks!

**Comment by 3Dickulus** [comment]
Ok. making a note to address that, looking forward to your animation ;)
