### ISSUE TITLE
mipmaps broken

### ISSUE THREAD

**Issue by claudeha** [3Dickulus/FragM#120]
**Describe the bug**
Trying to enable mipmaps (for anti-aliasing) leads to blank black image.

**To Reproduce**
1. Frag:
```
#version 130
#include "2D.frag"
uniform sampler2D Texture; file[image.png]
#TexParameter Texture GL_TEXTURE_MIN_FILTER GL_LINEAR_MIPMAP_LINEAR
vec3 color(vec2 p) { return texture(Texture, p).rgb; }
```
2. Load an image file (that isn't blank black).
3. Rebuild the frag.
4. See error: blank black screen
5. Delete the TexParameter line
6. Clear texture cache
7. Rebuild the frag
8. Texture is displayed, but without mipmapping.  Zoom out to see the aliasing.

**Expected behavior**
Mipmapping to work.

**Desktop (please complete the following information):**
 - OS: Debian Buster
 - Gfx card: AMD RX 580
 - Driver version: Vendor: X.Org / Renderer: Radeon RX 580 Series (POLARIS10, DRM 3.35.0, 5.4.3, LLVM 7.0.1) / GL Driver: 4.5 (Compatibility Profile) Mesa 18.3.6

**Additional context**
Very partial workround for less ugly images: use GL_NEAREST and bump up the subframe count.

**Comment by claudeha** [comment]
I looked at the source code to see if I need to fix it, and found a workaround/solution: specify
```
#TexParameter Texture GL_TEXTURE_MAX_LEVEL 1000
```
in addition to requesting mipmaps, otherwise you get a blank black image.

**Comment by 3Dickulus** [comment]
yes, you need to specify _all_ of the texture parameters after the sampler decl as in...

```
uniform sampler2D myTexture; file[test.png]
#TexParameter myTexture GL_TEXTURE_MAX_LEVEL 1000
#TexParameter myTexture GL_TEXTURE_WRAP_S GL_REPEAT
#TexParameter myTexture GL_TEXTURE_WRAP_T GL_REPEAT
#TexParameter myTexture GL_TEXTURE_MAG_FILTER GL_LINEAR
#TexParameter myTexture GL_TEXTURE_MIN_FILTER GL_LINEAR_MIPMAP_LINEAR
```
if any are missing you may have undefined result

keys...
```
GL_TEXTURE_WRAP_T
GL_TEXTURE_WRAP_S
GL_TEXTURE_MIN_FILTER
GL_TEXTURE_MAG_FILTER
GL_TEXTURE_MAX_LEVEL
GL_TEXTURE_MAX_ANISOTROPY
```

values...
```
GL_CLAMP
GL_REPEAT
GL_NEAREST
GL_LINEAR
GL_LINEAR_MIPMAP_LINEAR
GL_LINEAR_MIPMAP_NEAREST
GL_NEAREST_MIPMAP_LINEAR
GL_NEAREST_MIPMAP_NEAREST
```

when no texture parameters are defined by user mipmap is disabled.

**Comment by 3Dickulus** [comment]
yes, you need to specify _all_ of the texture parameters after the sampler decl as in...

```
uniform sampler2D myTexture; file[test.png]
#TexParameter myTexture GL_TEXTURE_MAX_LEVEL 1000
#TexParameter myTexture GL_TEXTURE_WRAP_S GL_REPEAT
#TexParameter myTexture GL_TEXTURE_WRAP_T GL_REPEAT
#TexParameter myTexture GL_TEXTURE_MAG_FILTER GL_LINEAR
#TexParameter myTexture GL_TEXTURE_MIN_FILTER GL_LINEAR_MIPMAP_LINEAR
```
if any are missing you may have undefined result

keys...
```
GL_TEXTURE_WRAP_T
GL_TEXTURE_WRAP_S
GL_TEXTURE_MIN_FILTER
GL_TEXTURE_MAG_FILTER
GL_TEXTURE_MAX_LEVEL
GL_TEXTURE_MAX_ANISOTROPY
```

values...
```
GL_CLAMP
GL_REPEAT
GL_NEAREST
GL_LINEAR
GL_LINEAR_MIPMAP_LINEAR
GL_LINEAR_MIPMAP_NEAREST
GL_NEAREST_MIPMAP_LINEAR
GL_NEAREST_MIPMAP_NEAREST
```

when no texture parameters are defined by user mipmap is disabled.
