### ISSUE TITLE
Strange error compiling on Ubuntu 18.04 (Bionic) (gcc 7.3.0)

### ISSUE THREAD

**Issue by 0joshuaolson1** [3Dickulus/FragM#13]
`make install`
```
/home/[REDACTED]/FragM/Fragmentarium-Source/Fragmentarium/GUI/DisplayWidget.cpp:1554:13: error:
      cannot initialize a variable of type 'GLfloat (*)[h][w][4]' with an rvalue
      of type 'GLfloat (*)[h][w][4]'
  ...myImgdata)[h][w][4] = (GLfloat (*)[h][w][4])malloc( (h*w*4*sizeof(GLfloat)) );
     ^                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/[REDACTED]/FragM/Fragmentarium-Source/Fragmentarium/GUI/DisplayWidget.cpp:1555:13: error:
      cannot initialize a variable of type 'GLfloat (*)[h][w][1]' with an rvalue
      of type 'GLfloat (*)[h][w][1]'
  ...myDepths)[h][w][1] = (GLfloat (*)[h][w][1])malloc( (h*w*sizeof(GLfloat)) );
     ^                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
12 warnings and 2 errors generated.
CMakeFiles/Fragmentarium-2.0.0.dir/build.make:224: recipe for target 'CMakeFiles/Fragmentarium-2.0.0.dir/Fragmentarium/GUI/DisplayWidget.cpp.o' failed
make[2]: *** [CMakeFiles/Fragmentarium-2.0.0.dir/Fragmentarium/GUI/DisplayWidget.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/Fragmentarium-2.0.0.dir/all' failed
make[1]: *** [CMakeFiles/Fragmentarium-2.0.0.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by 3Dickulus** [comment]
locally I use gcc version 4.8.5
CXX_FLAGS "-std=c++11"

**Comment by 0joshuaolson1** [comment]
Sorry for randomly asking for tech support.

That's already in CXX_FLAGS in `FragM/Fragmentarium-Source/build/CMakeFiles/Fragmentarium-2.0.0.dir/flags.make`.

I'm having trouble using gcc-4.8. I exported `CC=<gcc-4.8 OR cpp-4.8> CXX=<SAME>` and get:
```
-- The C compiler identification is unknown
-- The CXX compiler identification is unknown
-- Check for working C compiler: /usr/bin/cpp-4.8
-- Check for working C compiler: /usr/bin/cpp-4.8 -- broken
CMake Error at /usr/share/cmake-3.10/Modules/CMakeTestCCompiler.cmake:52 (message):
  The C compiler

    "/usr/bin/cpp-4.8"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /home/[REDACTED]/FragM/Fragmentarium-Source/build/CMakeFiles/CMakeTmp

    Run Build Command:"/usr/bin/make" "cmTC_2a854/fast"
    /usr/bin/make -f CMakeFiles/cmTC_2a854.dir/build.make CMakeFiles/cmTC_2a854.dir/build
    make[1]: Entering directory '/home/[REDACTED]/FragM/Fragmentarium-Source/build/CMakeFiles/CMakeTmp'
    Building C object CMakeFiles/cmTC_2a854.dir/testCCompiler.c.o
    /usr/bin/cpp-4.8    -o CMakeFiles/cmTC_2a854.dir/testCCompiler.c.o   -c /home/[REDACTED]/FragM/Fragmentarium-Source/build/CMakeFiles/CMakeTmp/testCCompiler.c
    cpp-4.8: fatal error: ‘-c’ is not a valid option to the preprocessor
    compilation terminated.
```

**Comment by claudeha** [comment]
@0joshuaolson1 I think `cpp` is the C preprocessor.  Try `c++` (for system default C++ compiler) or `g++` (for the GNU C++ compiler)

**Comment by 0joshuaolson1** [comment]
I wish I knew how - my default GCC isn't 4.8

**Comment by claudeha** [comment]
https://stackoverflow.com/questions/28094268/clang-cannot-initialize-a-variable-of-type-intdim2-with-an-rvalue-of-ty describes the error, unfortunately it seems C++14 Variable Length Arrays are not multidimensional-capable, some workarounds for single dimensions are presented in the answers (eg classes that overload [] or something along those lines).  Possibly easier to refactor to not use mutlidimensional arrays...

**Comment by 0joshuaolson1** [comment]
@claudeha I was looking for what that error could mean, thanks!

I don't think the real problem is the C++ version (I stated above that it's already specified), but some code is being incorrectly interpreted as C++ because I can't/won't globally downgrade to the gcc version Fragmentarium used to use...

**Comment by claudeha** [comment]
@0joshuaolson1 afaik FragM is C++ and not C.  I tried this (using `bash`) and got it to work with my non-default `g++-8` (also worked fine for me with `g++-7` as packaged by Debian, maybe Ubuntu broke things....

    cd FragM/Fragmentarium-Source
    rm -r build
    mkdir build
    cd build/
    export CC=/usr/bin/gcc-8 
    export CXX=/usr/bin/g++-8 
    cmake ..
    make

**Comment by 0joshuaolson1** [comment]
Can you do it with 4.8?

**Comment by claudeha** [comment]
my distro (Debian Buster, current testing, next stable) only goes back to `gcc-5`, which was first released in 2015.  `gcc-4.8.5` was released around the same time, but I think the compiler ABI changed between 4 and 5 making side-by-side installation impossible by this point in time...

**Comment by 3Dickulus** [comment]
Thanks for the input claudeha, I am using the default that comes with OpenSuSE Leap 42.3 and this probably means that my next OS upgrade will (assuming gcc version > 4.8) break FragM compile. Maybe it's time to re'n're the code base to take advantage of new stuff.

**Comment by claudeha** [comment]
I don't think so - I tested with both `gcc-7` and `gcc-8` on Debian and had no issues compiling FragM.  Must be some Ubuntu-specific breakage, if not a user error (still unsure).

**Comment by 0joshuaolson1** [comment]
> if not a user error (still unsure)

Hey! (I don't think so...)

**Comment by 0joshuaolson1** [comment]
I'll try a Debian-based distro and get back with y'all.

**Comment by 0joshuaolson1** [comment]
Cool, not just me.

> using cpp as CC or CXX

I couldn't find any other command associated with gcc-4.8 (though I could've looked harder).

**Comment by 0joshuaolson1** [comment]
Since you opened that other issue, I think I can close this one.

**Comment by 0joshuaolson1** [comment]
Oh wait, that's a PR.

**Comment by 0joshuaolson1** [comment]
Yay, it compiles for me on GCC 7.3. Now it makes the executable, but:
```
QApplication: invalid style override passed, ignoring it.
Segmentation fault (core dumped)
```
In `gdb`:
```
Starting program: /home/[REDACTED]/Fragmentarium-2.0.0/Fragmentarium-2.0.0
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffea823700 (LWP 7852)]
QApplication: invalid style override passed, ignoring it.
[New Thread 0x7fffe3fff700 (LWP 7853)]
[New Thread 0x7fff5ff53700 (LWP 7854)]

Thread 1 "Fragmentarium-2" received signal SIGSEGV, Segmentation fault.
0x00000000004a9a31 in Fragmentarium::GUI::DisplayWidget::init() ()
```
Sorry for bugging y'all again, but help!

**Comment by claudeha** [comment]
I tried `cmake -DCMAKE_BUILD_TYPE=Debug ..` but didn't change anything w.r.t. backtrace, so I modified the CMakeLists:

    diff --git a/Fragmentarium-Source/CMakeLists.txt b/Fragmentarium-Source/CMakeLists.txt
    index adc2f5c..500e175 100644
    --- a/Fragmentarium-Source/CMakeLists.txt
    +++ b/Fragmentarium-Source/CMakeLists.txt
    @@ -126,7 +126,7 @@ IF ( USE_OPEN_EXR )
       
     ENDIF (USE_OPEN_EXR)
     
    -SET ( CMAKE_CXX_FLAGS "-std=c++11 -Wall -Wextra" )
    +SET ( CMAKE_CXX_FLAGS "-std=c++11 -Wall -Wextra -g" )
     
     add_definitions ( -Wall )
     

and reproduced the crash:

    Thread 1 "Fragmentarium-2" received signal SIGSEGV, Segmentation fault.
    0x00005555555d4ef8 in QOpenGLFunctions_4_1_Core::glGetString (
        this=0x5555559f6b50, name=7936)
        at /usr/include/x86_64-linux-gnu/qt5/QtGui/qopenglfunctions_4_1_core.h:618
    618	    return d_1_0_Core->f.GetString(name);

and the solution for this (with current master) is to `cmake -DNVIDIAGL4PLUS=OFF ..`.  There is some discussion about GL versions on the forums, see https://fractalforums.org/fragmentarium/17/opengl-core-profile/1358

**Comment by 3Dickulus** [comment]
I think this is covered in https://github.com/3Dickulus/FragM/issues/3 **How do you build it?**

**Comment by 0joshuaolson1** [comment]
`-DNVIDIAGL4PLUS=OFF` worked for me. I was using `-DNVIDIAGL4PLUS=ON` as directed by the resource linked to by https://github.com/3Dickulus/FragM/wiki
