### ISSUE TITLE
Submodules not included in archive generated by github

### ISSUE THREAD

**Issue by 3Dickulus** [3Dickulus/FragM#130]
**Describe the bug**
Submodules not included in archive generated by github

**To Reproduce**
Download Zip from Code page

**Expected behavior**
A complete archive

**Desktop (please complete the following information):**
 - OS: All

**Additional context**
Travis build can create a complete archive at build time and tag as asset on releases page

**Comment by 3Dickulus** [comment]
`git clone --recursive ` gets all files

**Comment by 3Dickulus** [comment]
after some digging...
```
git archive -o release.zip HEAD
git submodule --quiet foreach 'cd $toplevel; zip -ru release.zip $sm_path'

```

creates a complete archive, no bash script needed, just 2 git commands

**Comment by 3Dickulus** [comment]
done, until github has a better option, there is an extra archive file with the release

**Comment by claudeha** [comment]
In my own projects I use `git subtree` instead of `git submodule`, more things "just work" with subtree, submodules cause lots of pain.  Example with explanation: https://github.com/pure-data/pd-lib-builder/blob/master/tips-tricks.md#git-subtree (this is where I got the idea to use it from)

**Comment by 3Dickulus** [comment]
hmmm... perhaps a noob's poor choice, converting from submodules to subtrees for the Examples hierarchy will just be part of my learning experience with github :P but for now I eat crow... of course github has a better option, submodules are for when you don't want to include a massive amount of other project code in your own repo or for using a pre-built install of something needed for compile, here is needed a smaller amount of code and it should be in the archived repo (duh!) and fortunately the users that have added repos as subfolders won't notice a  thing.
