### ISSUE TITLE
time slider can't be dragged to 0

### ISSUE THREAD

**Issue by claudeha** [3Dickulus/FragM#136]
**Describe the bug**
Time slider can't be dragged all the way to the start.

**To Reproduce**
1. Drag time slider away from left edge
2. Drag time slider all the back way to the left
3. See it clamp to 000s:01f
4. Pressing rewind it goes to the real start at 000s:00f

**Expected behavior**
Either dragging time slider goes all the way to 000s:00f, or rewind goes to 000s:01f.
I prefer to start counting at 0.

**Screenshots**
![time-slider-does-not-drag-to-zero](https://user-images.githubusercontent.com/10728495/80785984-0dae0200-8b7a-11ea-8119-5e680a1c3325.gif)

**Desktop (please complete the following information):**
 - OS: Debian Bullseye/Sid (testing/unstable)

**Comment by 3Dickulus** [comment]
oops the silliest things seem to be getting sneaking in... single step (up/down arrows) don't take it to 0 either... 

MainWindow.cpp lines 2079 and 2080 1 should be 0

**Comment by claudeha** [comment]
Thanks for the fix!  I didn't know about the arrow keys for this, so thanks for the knowledge too :)

**Comment by 3Dickulus** [comment]
by default all Qt widgets should have keyboard controls ;)
