### ISSUE TITLE
time rewind does not clear back buffer in progressive mode

### ISSUE THREAD

**Issue by claudeha** [3Dickulus/FragM#137]
**Describe the bug**
Pressing rewind (for the time slider) does not clear back buffer -> bad accumulation.

**To Reproduce**
1. Stop animation
2. Drag time slider to the middle
3. Start progressive rendering
4. Press rewind button
5. See error: the subframes from the "middle time" are not cleared before continuing to accumulate subframes from the "start time"

**Expected behavior**
back buffer to be cleared when rewinding (and subframe counter be reset)

**Screenshots**
![time-slider-rewind-does-not-clear-subframes](https://user-images.githubusercontent.com/10728495/80786541-e0faea00-8b7b-11ea-8e2e-54f973d5a38f.gif)

**Very Annoying Workaround**
1. press stop
2. switch to animation mode
3. switch to progressive mode
4. press play

**Desktop (please complete the following information):**
 - OS: Debian Bullseye/Sid (testing/unstable)

**Comment by 3Dickulus** [comment]
yes annoying, it will redraw properly as soon as you click the gl area, fixed with engine->requireRedraw(true); in rewind() and play() before engine->update()

**Comment by claudeha** [comment]
Thanks for the fix!
