### ISSUE TITLE
switching from (playing) animation to progressive mode doesn't clear subframes

### ISSUE THREAD

**Issue by claudeha** [3Dickulus/FragM#139]
**Describe the bug**
Switching from (playing) animation to progressive mode gives a mix of two time stamps, one subframe from the previous animation and then accumulation from the progresse mode

**To Reproduce**
1. Have an animated frag
2. Play animation
3. Switch to progressive mode
4. See error: there is one frame of animation left over from a different time stamp while the progressive frames accumulate

**Expected behavior**
Switch to progressive mode doesn't mix timestamps / i.e. it clears after the animation

**Desktop (please complete the following information):**
 - OS: Debian Bullseye/Sid testing/unstable

**Additional context**
Similar to https://github.com/3Dickulus/FragM/issues/137 ?

**Comment by 3Dickulus** [comment]
I took a 30 sec anim and reduced it to 1 sec, for dramatic changes, and I can't find the problem, not on nVidia at least.

the solution (I think) is again  `engine->requireRedraw(true);` in test for progressiveButton click

note: requireRedraw() only sets a flag to clear backbuffer when rendering starts
         it does not call redraw and can be set any number of times without penalty
         the render() call will only use the last flag state set before rendering begins.

**Comment by claudeha** [comment]
Needed a heavy frag to make it visible, otherwise the first bad subframe gets quickly lost in the accumulation.

Thanks for the fix,  can't reproduce it with latest develop branch.

**Comment by 3Dickulus** [comment]
:+1:
