### ISSUE TITLE
[discussion] where should animations start? frame 0 or frame 1?

### ISSUE THREAD

**Issue by claudeha** [3Dickulus/FragM#140]
**Describe the bug**
More of a request for discussion.

Recently my bug report #136 time slider can't be rewound to 0.
Now after the fix when doing a single frame animation render (start frame 1, end frame 1, can't select frame 0), the progress bar starts at 50%.  Single frame hires render (no animation selected) has frame 0/0 in the title bar of the progess dialog, and progress bar starts from 0.

**Expected behavior**
This is what needs to be decided.

Should animations start from frame 1 (as historically in Fragmentarium) or frame 0?

After a decision, any discrepencies can be fixed.

**Additional context**
Maybe changing everything to start at frame 0 is more work than fixing it up the other bits to start at frame 1?  As such I have no strong feelings about which is chosen, just want a decision and self-consistency within FragM.

**Comment by 3Dickulus** [comment]
thinking back... there was a reason for starting at frame 1, so frame 1 is actually frame 1 and last frame is actually frame n and not frame n-1 ... so 100 frames is 1-100 instead of 0-99

frame 0 was there as a "special" frame for something but can't remember what... 0th frame = not in animation so test renders could be done without anim-control interference ???

I should have just left it alone :-/

**Comment by claudeha** [comment]
On 06/05/2020 00:03, 3Dickulus wrote:
>
> I should have just left it alone :-/
>
Sorry for reporting the wrong bug - I suppose the bug should have been 
"rewind button sets frame to 0 instead of 1" instead of "time slider 
can't drag to 0"...

**Comment by 3Dickulus** [comment]
ahh semantics :P but it's not a bug ... thinking some more ... loading frag with animation features like keyframes and easing curves, initially applies Default preset which may or may not be part of the animation, rendering 0th frame at startup means no anim control from keyframes or easingcurves but the applied settings are valid, ensures some consistency in the startup load/compile/render process ???  I'll have to do some digging to verify but at this stage my recollection is that there was a reason for that behaviour. (thanks for jogging my memory, should nail that down and document it in comments or wiki or something)
