### ISSUE TITLE
wiki

### ISSUE THREAD

**Issue by adammaj1** [3Dickulus/FragM#149]
I can't find info in wiki about : 

- How to run progrm aform console ? 

- how to save image ( graphic file like  png)

TIA

**Comment by adammaj1** [comment]
I run it 
cd /Fragmentarium-2.5.3
 ./Fragmentarium-2.5.3 -l en

( there is no pl file )

**Comment by adammaj1** [comment]
to save :
MainMenu/Render/High resolutiona and animation render
change Render tiles

-------------

Is it 1600x900 maximal resolution?

**Comment by 3Dickulus** [comment]
https://github.com/3Dickulus/FragM/wiki/02.-Usage

Maximum resolution is determined by your gfx card, 16384x16384 for mine, FragM will report maximum texture size in the log tab at startup. Output image resolution is controlled by tile size and a ^2 multiplier, top slider in the High Resolution and Animation dialog.
https://github.com/3Dickulus/FragM/wiki/05.-Dialogs

To render a single image f rom this dialog...

set Start frame and End frame to 1
un-check Animation box
choose a filename (no path just name)
un-check the last (bottom) 3 boxes
select [ OK ]

...this will render a single hires image in the same folder as the main program using the  name you provide.

**Comment by 3Dickulus** [comment]
_mkdir Fragmentarium-Source/build_
_cd Fragmentarium-Source/build_
**cmake-gui ..**  <<< select **configure**, set options like install path here, select **generate**, then quit
**make install**   <<< will install Fragmentarium in the path you specified above with **ALL** of the support files

English is the default language, check the Translation folder in the source tree for the language files, make install should generate a _Languages/_ folder in the install path next to the executable.

**Comment by adammaj1** [comment]
I create bash file f
`
#!/bin/bash
cd ~/Fragmentarium-2.5.3
./Fragmentarium-2.5.3
`

and run 
./f
