### ISSUE TITLE
Segmentation Fault in Fedora release 28

### ISSUE THREAD

**Issue by gsohler** [3Dickulus/FragM#15]
Hi,

I have cloned your FragM  git repository
and compiled doing
mkdir build ; cd build
cmake ..
make
sudo make install
./Fragmentarium-2.0.0 -v
Fragmentarium 

strace ./Fragmentarium-2.0.0

It comes out with an segmentation fault:

poll([{fd=3, events=POLLIN|POLLOUT}], 1, -1) = 1 ([{fd=3, revents=POLLOUT}])
writev(3, [{iov_base="7\0\4\0\f\0\0\1\5\0\0\1\0\0\0\0007\20\4\0\r\0\0\1\5\0\0\1\0\0\0\0"..., iov_len=56}, {iov_base=NULL, iov_len=0}, {iov_base="", iov_len=0}], 3) = 56
futex(0x7ffe0ffa0e68, FUTEX_WAIT_PRIVATE, 0, NULL) = 0
futex(0x19e0f78, FUTEX_WAKE_PRIVATE, 1) = 0
shmget(IPC_PRIVATE, 73728, IPC_CREAT|0777) = 21266453
shmat(21266453, NULL, 0)                = 0x7fbee8080000
shmctl(21266453, IPC_RMID, NULL)        = 0
shmdt(0x7fbf72d28000)                   = 0
shmctl(21233684, IPC_RMID, NULL)        = -1 EINVAL (Invalid argument)
mmap(NULL, 4096, PROT_READ|PROT_WRITE|PROT_EXEC, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fbf880e9000
--- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0x50} ---

what could go wrong in my place ?

**Comment by 3Dickulus** [comment]
I have just gone through these steps   ...  compiles and runs as expected here

git clone https://github.com/3Dickulus/FragM.git master
cd master/Fragmentarium-Source/
mkdir build
cd build
cmake ..
make
sudo make install

this creates **/usr/local/Fragmentarium-2.0.0/**

cd /usr/local/Fragmentarium-2.0.0/
./Fragmentarium-2.0.0                           success

by default it compiles with NVIDIAGL4PLUS = ON if you don't have an nVidia gfx card or your gfx card is not capable of GL v4+ it may crash, you can edit the CMakeLists.txt file at line 35 or install cmake-gui and use it just like cmake as in...

cd build
cmake-gui ..

there you can adjust options before generating the Makefile

**Comment by gsohler** [comment]
Hi,
In fact, I dont have a good Graphics card in my computer
Actually just yesterday i found out, that the thing that i bought is a fake

https://devtalk.nvidia.com/default/topic/989778/linux/nvidia-drivers-378-09-fails-to-build-fatal-modpost-gpl-incompatible-module-nvidia-drm-ko-uses-gpl-only-symbol-mutex_destroy-/post/5277783/#5277783

would be nice if could you output an "unsupported" message rather than a segfault 

Guenther

**Comment by 3Dickulus** [comment]
Have you tried to set NVIDIAGL4PLUS = OFF in the CMakeLists.txt file at line 35, this turns off some nVidia specific options.

I can't possibly know or anticipate all of the anomalies for every card manufacturer and computer configuration and , no doubt, they won't fail in the same bit of code so a test may return true but the program might still crash.

Sorry to hear you got burned with a fake :(

**Comment by gsohler** [comment]
Hi Dickulus ;)

Yesterday I was able to try with NVIDIAGL4PLUS = OFF and it works now!
However its NO fun and i rather wait for my new NO_FAKE Card before I explore all the examples.

Thank you and best regards
