### ISSUE TITLE
error line off-by-one

### ISSUE THREAD

**Issue by claudeha** [3Dickulus/FragM#157]
**Describe the bug**
Sometimes (not always) the error line reported by the shader compiler is off by one.

**To Reproduce**
1. Load attached off-by-one/main.frag
2. See error reported one line after the error text

**Expected behavior**
Error line matches the error text.

**Desktop (please complete the following information):**
 - OS: Debian Bullseye
 - GPU: AMD Radeon RX 580
 - Driver: Vendor: X.Org / Renderer: Radeon RX 580 Series (POLARIS10, DRM 3.39.0, 5.9.0-3-amd64, LLVM 11.0.0) / GL Driver: 4.6 (Compatibility Profile) Mesa 20.2.3

**Additional context**
It doesn't always occur.  May be driver dependent?

**Attachments**
This one works as expected: [not-off-by-one.zip](https://github.com/3Dickulus/FragM/files/5654761/not-off-by-one.zip)
This one has error off by one: [off-by-one.zip](https://github.com/3Dickulus/FragM/files/5654762/off-by-one.zip)

**Comment by claudeha** [comment]
Adding an empty line at the start of the file switches the direction of this off-by-one:
[after.frag.txt](https://github.com/3Dickulus/FragM/files/5654919/after.frag.txt)
[before.frag.txt](https://github.com/3Dickulus/FragM/files/5654920/before.frag.txt)

**Comment by 3Dickulus** [comment]
insert `#line 2` at line 2 corrects off-by-one frag

my attempt to get this sorted out is in void Preprocessor::parseSource() roughly the first 200 lines

**Comment by 3Dickulus** [comment]
Found the cause...

case: hasIncludes, !hasVertexCode, vers > 200, the inserted #line directive must account for how many #include statements

fix: @ line 165 in Preprocessor.cpp add `int incCount = 0;` and @ line 184 change...
                                `in.insert(i+1, QString("#line %1 %2").arg(i).arg(sf));`
to...
                                `in.insert(i+1, QString("#line %1 %2").arg(i-(incCount-1)).arg(sf));`
and 

after line 190 add...
                                `incCount++;`

if the value is less than 0 it will prepend, if the value is greater than line count it will append.

Here is my error line test suite, after making the adjustment these tests all get the right line numbers
testing errors in vertex and fragment parts of main shader and buffershader...

[Error-Line-Tests.zip](https://github.com/3Dickulus/FragM/files/5663297/Error-Line-Tests.zip)

the script is hardcoded for paths but not hard to figure out, in Fragmentarium folder I have FragMTestSuite/Error-Line-Tests/ that contains all of the frags and the script so in my setup I cd to where Fragmentarium executable lives and run the script like...

`sh ./FragMTestSuite/Error-Line-Tests/errorLineTest.sh ./Fragmentarium-2.5.4`

...passing it the name of the executable I want to test.
