### ISSUE TITLE
bad error reporting behaviour with repeated builds

### ISSUE THREAD

**Issue by claudeha** [3Dickulus/FragM#161]
**Describe the bug**
Building twice a shader with errors in the buffershader, without making any changes to anything in between, only shows the error the first time.

**To Reproduce**
1. Open new tab, usually displaying 8 balls, build.
2. Put an `error;` in the `BufferShader.frag` and save it.
3. Build, see error displayed in log.
4. Build again, see no error displayed in log (so it appears to have been successful), rendering proceeds as if there is no buffer shader at all (screen soon goes white from accumulation of subframes, it has not been successful after all).

**Expected behavior**
Errors to be displayed accurately.

**Desktop (please complete the following information):**
 - OS: Debian Bullseye (testing)
 - Gfx: AMD Radeon RX 580
 - Driver: Vendor: X.Org / Renderer: Radeon RX 580 Series (POLARIS10, DRM 3.39.0, 5.9.0-4-amd64, LLVM 11.0.0) / GL Driver: 4.6 (Core Profile) Mesa 20.2.3

**Additional context**

**Comment by 3Dickulus** [comment]
I see this on second build, but only if no changes are made to the source, it should report the same error.
![Screenshot_20201209_185201](https://user-images.githubusercontent.com/4978723/101715248-f14b3f80-3a4f-11eb-89df-9ec80df21f21.png)
...and will not engage subframe rendering, stays in "stop" mode

are these recent tests all done with up-to-date files from the repo?

**Comment by 3Dickulus** [comment]
these user actions...

 Menu: Render->Compile GLSL
 Keyboard: F5 hotkey
 Toolbar: Build button

... always rebuild fragment source
