### ISSUE TITLE
crash when moving camera after text editor closed

### ISSUE THREAD

**Issue by claudeha** [3Dickulus/FragM#162]
**Describe the bug**
FragM segfaults when navigating the camera when all the text editor tabs have been closed.

**To Reproduce**
1. Start FragM
2. Close all text editor tabs.
3. Drag camera view
4. See error: crash

**Expected behavior**
No crash.

**Desktop (please complete the following information):**
 - OS: Debian Buster
 - GPU: NVIDIA G105M
 - Driver: Vendor: NVIDIA Corporation / Renderer: GeForce G 105M/PCIe/SSE2 / GL Driver: 3.3.0 NVIDIA 340.108

**Additional context**
This fix prevents the crash (but changing post variables now restart rendering; no big deal...)
```
diff --git a/Fragmentarium-Source/Fragmentarium/GUI/MainWindow.cpp b/Fragmentarium-Source/Fragmentarium/GUI/MainWindow.cpp
index 6232295..eb98252 100644
--- a/Fragmentarium-Source/Fragmentarium/GUI/MainWindow.cpp
+++ b/Fragmentarium-Source/Fragmentarium/GUI/MainWindow.cpp
@@ -885,6 +885,7 @@ void MainWindow::showWelcomeNote()
 bool MainWindow::isChangedUniformInBuffershaderOnly()
 {
     if(!engine->hasShader() || !engine->hasBufferShader()) return false;
+    if(!getTextEdit()) return false;
     QStringList lastSet = getTextEdit()->testParms().split("\n");
     bool inBufferShaderOnly = false;
     if (!lastSet.isEmpty()) {
```

**Comment by 3Dickulus** [comment]
a better fix would be to shut down all attempted shader program interaction when there are no tabs open.

no tabs means it shouldn't be calling isChangedUniformInBuffershaderOnly()
