### ISSUE TITLE
window title and tab tooltip not updated when saving under a different name

### ISSUE THREAD

**Issue by claudeha** [3Dickulus/FragM#165]
**Describe the bug**
I opened `00-HubbardTree.frag`, saved it as `00-Vein.frag` in preparation for edits: tab title is updated correctly, but window title and tab tooltip remain the obsolete values.

**Expected behavior**
Tab tooltip to show current save path, window title to show `00-Vein.frag` without the "modified" asterisk

**Screenshots**
![bug](https://user-images.githubusercontent.com/10728495/106289880-b42a4f00-6241-11eb-86cf-0767f940a905.png)

**Desktop (please complete the following information):**
 - OS: Debian Buster w/ XFCE
 - GPU: NVIDIA G105M
 - Driver: Vendor: NVIDIA Corporation / Renderer: GeForce G 105M/PCIe/SSE2 / GL Driver: 3.3.0 NVIDIA 340.108

**Additional context**
Tested with a slightly-behind version; will upgrade to latest this weekend and report back in case it is already fixed...

**Comment by 3Dickulus** [comment]
not fixed yet, first time I've noticed this, I know what it is though, so should be fixed momentarily :)

**Comment by 3Dickulus** [comment]
fixed: insert line 385 (in my current version) MainWindow.cpp
`        tabBar->setTabToolTip(index,fileName);`
the window title should be ProgramName Version Revision Codename
