### ISSUE TITLE
splash screen crash

### ISSUE THREAD

**Issue by claudeha** [3Dickulus/FragM#168]
**Describe the bug**
FragM crashes on launch, something to do with splash screen.

**To Reproduce**

1. try to start FragM
2. See error

```
Thread 1 "Fragmentarium-2" received signal SIGSEGV, Segmentation fault.
0x00007ffff76e1ab0 in QWidget::close() () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
(gdb) bt
#0  0x00007ffff76e1ab0 in QWidget::close() () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#1  0x0000555555606ee5 in Fragmentarium::GUI::MainWindow::removeSplash() (this=this@entry=0x555555a26f60)
    at /home/claude/code/github.com/3Dickulus/FragM/Fragmentarium-Source/Fragmentarium/GUI/MainWindow.cpp:3401
#2  0x0000555555616f6c in Fragmentarium::GUI::MainWindow::init() (this=0x555555a26f60) at /home/claude/code/github.com/3Dickulus/FragM/Fragmentarium-Source/Fragmentarium/GUI/MainWindow.cpp:718
#3  0x00005555556177cd in Fragmentarium::GUI::MainWindow::MainWindow(QWidget*) (this=0x555555a26f60, parent=<optimized out>)
    at /home/claude/code/github.com/3Dickulus/FragM/Fragmentarium-Source/Fragmentarium/GUI/MainWindow.cpp:100
#4  0x00005555555bb69f in main(int, char**) (argc=<optimized out>, argv=0x7fffffffdf70) at /home/claude/code/github.com/3Dickulus/FragM/Fragmentarium-Source/Fragmentarium/Main.cpp:296
(gdb) up
#1  0x0000555555606ee5 in Fragmentarium::GUI::MainWindow::removeSplash (this=this@entry=0x555555a26f60) at /home/claude/code/github.com/3Dickulus/FragM/Fragmentarium-Source/Fragmentarium/GUI/MainWindow.cpp:3401
3401	        splashWidget->finish(this);
```

**Expected behavior**
No crash, whether if the splash screen is shown or not (personally I prefer not).

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Debian Bullseye
 - GPU: AMD RX 580
 - Driver version: cannot access it from FragM (not sure it's relevant here)

**Additional context**

I have a local branch in which I deleted all the splash-related code I could find, so I can work on other things...

**Comment by claudeha** [comment]
Seems to be Qt 5.15.2+dfsg-4 on my system.

**Comment by 3Dickulus** [comment]
hm.. not a problem here, no crash, splash shows, splash goes away, program runs ???

I'm not a big fan of the splash screen as it serves no purpose or function, the intent is to give a user something to look at while the program sets up... which is fine for an app that does a lot of setup or needs to get the user's attention while it fumbles around in the background looking for your account and banking information :-/

you are using 210215? looking at the code now...

**Comment by claudeha** [comment]
Was on develop latest: `commit b4dcc1660b737e64a4eaea6a925240864efe85c3 (tag: v2.5.5-210215, origin/develop, origin/HEAD, ...`

**Comment by 3Dickulus** [comment]
Fixed. incoming commit...

**Comment by Zi7ar21** [comment]
The new release crashes for me too. I don't even get to see the splash screen, nothing appears to happen after launching it.

**Comment by Zi7ar21** [comment]
BRUH MOMENT
Hi 3Dickulus
![image](https://user-images.githubusercontent.com/41303821/108454190-28488900-7229-11eb-84a1-2a4925e45490.png)

**Comment by 3Dickulus** [comment]
Just fixed it... rebuilding release binaries soon...
