### ISSUE TITLE
Windows build of Fragmentarium 2.5.6 crashes at startup

### ISSUE THREAD

**Issue by jee7** [3Dickulus/FragM#179]
**Describe the bug**
Downloaded the latest release of Fragmentarium (v.2.5.6) from here: [https://github.com/3Dickulus/FragM/releases](https://github.com/3Dickulus/FragM/releases). When I unzip and run the Fragmentarium-2.5.6.exe file, I get a "not responding" status and the program fails to start. I initially got a memory access violation error too, but cannot reproduce it.

**To Reproduce**
1. Go to [https://github.com/3Dickulus/FragM/releases](https://github.com/3Dickulus/FragM/releases) 
2. Click on [Fragmentarium-2.5.6-211212-winex.7z](https://github.com/3Dickulus/FragM/releases/download/v2.5.6-211212/Fragmentarium-2.5.6-211212-winex.7z)
3. Download the file
4. Unzip the package
5. Run the Fragmentarium-2.5.6.exe file.
6. Splash screen opens.
7. See error (program not responding or maybe memory violation)

**Expected behavior**
Fragmentarium should start without problems.

**Screenshots**

![image](https://user-images.githubusercontent.com/3455815/146375646-ed4fccfb-765f-4878-8fa3-007af4c2f2e3.png)

![image](https://user-images.githubusercontent.com/3455815/146376060-17cb3a8c-3b8a-445b-adfd-7be5797d29c5.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Enterprise
 - Intel(R) HD Graphics 4000
 - Driver version: 10.18.10.5161

**Additional context**
I also tried on Windows 8.1 with non-integrated graphics, same issue. Does not matter if I enable or disable the autorun on the "Autorun on Load" popup, which appears after the program has crashed once before. The exe file does not show the Fragmentarium logo as the file icon either.

**Comment by 3Dickulus** [comment]
ahh the gradient editor requires Qt 5.12 but compiled against 5.9 with no  complaints... attempting to update Qt version under wine on linux...

**Comment by jee7** [comment]
Don't know if I'm doing something wrong, but now it doesn't start either. No error this time, just doesn't do anything.

https://user-images.githubusercontent.com/3455815/146663367-dcf2dad9-1d37-4435-b99e-3dc6ff63ce18.mp4

**Comment by 3Dickulus** [comment]
Ok not fixed ???

is there a dialog open waiting for input behind the splash screen? with text...

    "It looks like the Fragmentarium program crashed during the last startup."
    "To prevent repeated crashes, you may choose to disable 'Autorun on Load'."
    "This option may be re-enabled through Preferences"

I ask because it happened after a crash on linux wine version, not sure why the splash obscured the dialog but it will sit there forever until "OK"d ... on linux Alt key + LMB click & drag allows moving the splash out of the way.

Will look at setting the timeout on the splash screen earlier and/or rearrange the logic for the "crashed on last run" dialog.

**Comment by 3Dickulus** [comment]
572b925 sets dialog stay on top hint so it can't hide behind splash screen

**Comment by jee7** [comment]
Yes, that was it! It works now. Thank you. :)

**Comment by 3Dickulus** [comment]
cheers!
