### ISSUE TITLE
Is there any homepage for FragM like there was for Fragmentarium

### ISSUE THREAD

**Issue by ghost** [3Dickulus/FragM#180]
Is there any homepage for FragM like there was for Fragmentarium or is this repo essentially the homepage?

**Comment by 3Dickulus** [comment]
Yes. Not quite like the Fragmentarium page created by Syntopia (still the best resource for FragM too)

I have created a wiki that has more up-to-date information about the additional features and functions that have been added... new menu items , new widgets, scripting functions etc...
https://github.com/3Dickulus/FragM/wiki

edit: Could use some updating and refining ;) there are a few details that might be missing or some things that could be explained or demonstrated a bit better... wip

**Comment by ghost** [comment]
Oh wow, the wiki looks great, thanks for all the info I really appreciate it 😄
