### ISSUE TITLE
Nothing showing

### ISSUE THREAD

**Issue by fractalf** [3Dickulus/FragM#182]
Can't get anything showing.
I'm a shader noob, but experienced developer/geek.
Thanks for any input!

Is this because I don't have a proper gfx card?

LENOVO ThinkPad L15 Gen 1 (20U3000SMX)

```sh
> uname -a                                           
Linux tinky 5.4.0-105-lowlatency #119-Ubuntu SMP PREEMPT Mon Mar 7 19:29:30 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

> lsb_release -a
No LSB modules are available.
Distributor ID:	Linuxmint
Description:	Linux Mint 20.1
Release:	20.1
Codename:	ulyssa
```

![image](https://user-images.githubusercontent.com/5707457/164285651-e00d4713-e024-45d0-aeda-4b1358363ab5.png)

**Comment by 3Dickulus** [comment]
Yeah, I think it would cook your ThinkPad if it did run. FragM will use 100% GPU for extended periods depending on the render task. Sorry, it was never intended to run on labtop or notebook style machines. Recommend a discrete gfx card preferably nVidia (that's what the development machine has) reportedly works on ATI too but not good for intel or APU chips.

**Comment by fractalf** [comment]
Ok, thank you :) ..I was looking for something like an "offline shadertoy", search goes on..

**edit**
If others come across this, I found an alternative here: https://github.com/dfranx/SHADERed

**Comment by claudeha** [comment]
try adding "#version 330 core" at the top of the shader - at least on my Debian Linux with Mesa (amdgpu) I just get blank screen in FragM if I don't specify a core profile...
