### ISSUE TITLE
cmake 3.20 is too new

### ISSUE THREAD

**Issue by claudeha** [3Dickulus/FragM#186]
**Describe the bug**
Debian Bullseye (aarch64) does not have cmake 3.20, only cmake 3.18.4

**To Reproduce**
Try cmake
See it complain

**Expected behavior**
cmake 3.18 seems new enough to build, no issues after editing cmakelists.txt to reduce required version

**Additional context**
Android tablet running UserLAnd

**Comment by 3Dickulus** [comment]
tnx... but don't we want the latest and greatest cutting edge... ok 3.18 it is ;)
