### ISSUE TITLE
Undefined variable "time" when use #define USE_IQ_CLOUDS

### ISSUE THREAD

**Issue by neozhaoliang** [3Dickulus/FragM#194]
Hi, it looks like when using the "DE-Kn2cr11.frag" included in this repo, it has conflicts with the macro `#define USE_IQ_CLOUDS`, it reports the error "DE-Kn2cr11.frag(734): error C1503: undefined variable "time"". Is it because here the uniform `time` is commented out?

https://github.com/3Dickulus/Fragmentarium_Examples_Folder/blob/master/Include/DE-Kn2cr11.frag#L728

**Comment by 3Dickulus** [comment]
"time" is a user optional variable, clouds were added to DE-Kn2cr11.frag without this consideration and had declared "time" internally causing conflicts in other frags.

You can find it in the menu **Edit-> Insert Command->Special Uniforms**

Simple solution is to put it in the user fragment before including Kn2cr11, the parts that use "time" in Kn2cr11 should be wrapped in `#ifdef time ... #endif ` statements so that it doesn't cause an error if time is not declared... but they are not, will try to get that done, in the mean time...

```
...
uniform float time;
#include "DE-Kn2cr11.frag"
...
```

this works.

 You could also uncomment the line in  Kn2cr11 but that may cause problems in other user frags

**Comment by neozhaoliang** [comment]
Thank you! I have solved this problem with your help. I am working hard to make my frag files compatible with FragM, so that users can run them without manual modifications.

**Comment by 3Dickulus** [comment]
the "time" variable with USE_IQ_CLOUDS is for making the clouds drift across the sky when animating the scene

**Comment by neozhaoliang** [comment]
Got that. Your replies are patient and very detailed. Thank you for all these.
Another problem I'm having is, when I load a frag file to FragM which I have tuned the settings in Fragmentarium, the rendering quality looks very low:
![图片](https://user-images.githubusercontent.com/23307174/219904308-7134b67c-8642-4e75-a11b-0161aa93f9eb.png)
Is there a way that I can set the rendering quality in the preview window?

And for [this file](https://github.com/neozhaoliang/Hyperbolic-Honeycombs/tree/main/honeycombs-DERayTracer) using the `DE-Raytracer`, when loaded to FragM, the colors are not shown correctly:
![图片](https://user-images.githubusercontent.com/23307174/219904762-8f0a774b-604f-47bd-b097-9efd3f2b1ab3.png)
Is it because the way some parameters working have changed?

**Comment by 3Dickulus** [comment]
it looks like you have neglected to turn on frame accumulation "progressive rendering" so you are seeing a single frame
![single-frame](https://user-images.githubusercontent.com/4978723/219905197-6b43dc98-4744-44e5-8cba-ca1be00d16d8.png)
![accumulated-frames](https://user-images.githubusercontent.com/4978723/219905199-652dc3f3-cc75-4203-845c-bf2cbed1e571.png)

**Comment by 3Dickulus** [comment]
![wrong-saturation](https://user-images.githubusercontent.com/4978723/219906288-968c6449-819a-4a4b-8ad4-1cda9c0d1af5.png)
![with-saturation](https://user-images.githubusercontent.com/4978723/219906284-7070b0cd-b9dd-4c46-a129-cf6998e26ac3.png)

**Comment by neozhaoliang** [comment]
Thank you so much! I have already solved these problems. It turns out that some of my settings were not very reasonable. I will update the settings in the repository later.
