### ISSUE TITLE
The animation render doesn't rename the frames incrementally

### ISSUE THREAD

**Issue by sam31415** [3Dickulus/FragM#195]
The animation render doesn't rename the frames incrementally, causing each frame to overwrite the previous one and resulting in a single image.

I solved this for my use by running a python script at the same time that will rename any image produced before the next one overwrites it. But it would be nicer if this could be fixed.

**Comment by 3Dickulus** [comment]
It seemed to work just fine the last time I rendered an animation... looking into it this weekend... possibly sooner if time permits.

**Comment by 3Dickulus** [comment]
hm... just did a very quick test and it works as expected.

Select the menu item **Render->High Resolution and Animation Render** and make the dialog look like this... (but make  end frame small, like 30 or something)
![High-Resolution-and-Animation-Render](https://user-images.githubusercontent.com/4978723/221068664-d15b75d3-86da-46e5-a71a-1a3b12ee045f.png)
...then select **OK**

This should create a folder named **animtest_Files** with the images in a folder named **images**

**Comment by 3Dickulus** [comment]
That is just a quick test, it should work fine for any size, number of tiles, number of subframes and number of frames

**Comment by sam31415** [comment]
Thank you for the very quick reply. Interesting. I was passing an absolute path. If I pass a relative path like yours, it saves the images in the folder containing the executable and indeed, it does number them properly. So the issue is with the absolute path. Can you reproduce that?

**Comment by 3Dickulus** [comment]
That is just a quick test, it should work fine for any size, number of tiles, number of subframes and number of frames.

I can not reproduce, it saves when full path is specified and increments image filename properly.

![High-Resolution-and-Animation-Render-test-2](https://user-images.githubusercontent.com/4978723/221326610-9c7a88e6-7019-420f-9ce3-934ef53ada52.png)

What OS? Try compiling from source?

**Comment by sam31415** [comment]
I'm using Windows 11 with the windows distribution. I didn't try to compile. (I'm not familiar with the procedure, this would require quite some effort.)

Anyway, using relative paths/my python script solves the problem for me, so feel free to close.

In any case, thanks for being so responsive!
