### ISSUE TITLE
Is "subframe" equivalent to "iFrame" in shadertoy?

### ISSUE THREAD

**Issue by neozhaoliang** [3Dickulus/FragM#199]
Hi, as there is no discussion tag in this repo, please pardon me for posting a question (not an issue) here:

> Q: is the uniform `subframe` equivalent to `iFrame` in shadertoy? That is, it counts the index of the current frame?

**Comment by 3Dickulus** [comment]
No, subfame is the count for accumulation frames per final image frame.

**Comment by neozhaoliang** [comment]
Thanks!
