### ISSUE TITLE
Think about refactoring MainWindow.cpp and DisplayWidget.cpp

### ISSUE THREAD

**Issue by valera-rozuvan** [3Dickulus/FragM#2]
Any plans for doing something about the extra large CPP files:

- [MainWindow.cpp](https://github.com/3Dickulus/FragM/blob/master/Fragmentarium-Source/Fragmentarium/GUI/MainWindow.cpp) [3463 lines]
- [DisplayWidget.cpp](https://github.com/3Dickulus/FragM/blob/master/Fragmentarium-Source/Fragmentarium/GUI/DisplayWidget.cpp) [2159 lines]

If yes - can this work be split up? Maybe I can help with something.

**Comment by 3Dickulus** [comment]
Yes,
I did put TextEdit into .cpp and .h files and added almost everything in ThirdPartyCode folder

LOC  FILENAME
    91 asmbrowser.cpp
    45 asmbrowser.h
    99 EasingAnimation.h
   525 EasingDialog.ui
   328 EasingWindow.cpp
   131 EasingWindow.h
   193 hdrloader.cpp <<<
    22 hdrloader.h <<<
   436 Highlighter.h
   299 qdoublerangeslider.cpp
    96 qdoublerangeslider.h
  1014 qrangeslider.cpp
   251 qrangeslider.h
   271 QtSpline.cpp
    98 QtSpline.h
   291 TimeLine.cpp
    67 TimeLineDialog.ui
    87 TimeLine.h
   309 VideoDialog.cpp
    54 VideoDialog.h
   253 VideoDialog.ui
  4960 total

hdrloader.cpp and hdrloader.h are from the original master git repo for v0.9.53
OpenEXR can read hdr images so these files may be obsolete now.

I also dropped the original SyntopiaCore/Math/ (7) files and now use the Qt functions provided by QVector(n)D and QMatrix(n)x(n)

maybe some of the Load and Save functions can be moved to the Filemanager class ? or a header file ?
