### ISSUE TITLE
textures don't load when running a script from the command line

### ISSUE THREAD

**Issue by claudeha** [3Dickulus/FragM#26]
black screen, even doing it twice doesn't work

    // build shader, in case autorun is disabled in preferences
    app.initializeFragment();
    app.applyPresetByName(preset);
    // again, in case preset changed things that need rebuilding
    app.initializeFragment();
    app.applyPresetByName(preset);

workaround: intializing shader in the GUI and applying preset (rebuilding as necessary) gets texture working, and then running the script within it works ok

**Comment by 3Dickulus** [comment]
is this wrt SkyBox or textures in general?

**Comment by claudeha** [comment]
i am using a 2D equirectangular texture

**Comment by claudeha** [comment]
I see it is already known, sorry for the duplication.. https://fractalforums.org/fragmentarium/17/benchmarking-with-v2-5-0/2064/msg10299#msg10299

**Comment by 3Dickulus** [comment]
Using nVidia card textures do load when running in script mode and when switching tabs, see latest patch and let me know if Mesa still has problems with this.

**Comment by claudeha** [comment]
No, it is not fixed for me :(  steps to reproduce (with `raymond/examples/Bubbles.frag` and `AnotherTileSizeBenchmark.frag` from the forums):

0. disable autorun in prefs
0. `cd ~/opt/fragm/Fragmentarium-2.5.0`
0. `./Fragmentarium-2.5.0  -s ~/opt/fragm/Fragmentarium-2.5.0/fqScript/AnotherTileSizeBenchmark.fqs ~/code/code.mathr.co.uk/raymond/examples/Bubbles.frag`

expected output: images with Berlin in the background
actual output: totally black images (no texture loaded)

something is trying to set the sampler it seems, but it no work:

    $ grep Berlin stderr.log | uniq -c
         23 "SAMPLER_2D" 	 "Background" "../images/Berlin.equi.jpg"
