### ISSUE TITLE
stuck textures when switching back and forth with presets

### ISSUE THREAD

**Issue by claudeha** [3Dickulus/FragM#27]
Steps to reproduce (using Raymond `examples/SkyBox.frag` https://code.mathr.co.uk/raymond/blob/d0caf605bcc71dd648c88b173edbb5d638a68574:/examples/SkyBox.frag#l87 , if necessary I can provide a more minimal test case)

0. `git clone https://code.mathr.co.uk/raymond.git`
0. download textures using the scripts in `raymond/images/`
0. in preferences: disable autorun, set include path to add `.../raymond/include/`
1. load `raymond/examples/SkyBox.frag`
2. build
3. apply preset Default
4. build (shows black)
5. apply preset Berlin
6. build (shows Berlin)
7. apply preset Paris
8. build (shows Paris
9. apply preset Berlin
10. build (shows Paris - bug!)

expected: Berlin is visible
what happens: Paris is visible and stuck (can't switch back to Berlin any more).

awkward workaround:

1. apply preset Paris
2. build
3. select Clear Texture Cache from the menu
4. apply preset Berlin
5. build

now it shows Berlin again

**Comment by 3Dickulus** [comment]
did you check the log window? I get this when loading your skybox example

Could not create fragment shader: 0(234) : warning C7555: 'varying' is deprecated, use 'in/out' instead
0(235) : warning C7555: 'varying' is deprecated, use 'in/out' instead
0(236) : warning C7555: 'varying' is deprecated, use 'in/out' instead
0(237) : warning C7555: 'varying' is deprecated, use 'in/out' instead
0(238) : warning C7555: 'varying' is deprecated, use 'in/out' instead
0(2262) : error C1104: too many parameters in function call
0(2268) : error C1104: too many parameters in function call
0(2300) : error C0000: syntax error, unexpected ',', expecting "::" at token ","

fails to compile :(

**Comment by claudeha** [comment]
yes of course, it compiles here - this is before setting the image presets:

    X.Org Radeon RX 580 Series (POLARIS10, DRM 3.26.0, 4.18.19, LLVM 6.0.1)
    Using GL version 4.5 Compatibility profile
    
    Available image formats: bmp, cur, ico, jpeg, jpg, pbm, pgm, png, ppm, xbm, xpm, exr
    
    Parse: /home/claude/opt/fragm/Fragmentarium-2.5.0/raymond/examples/SkyBox.frag
    Including file: /home/claude/code/code.mathr.co.uk/raymond/include/Raymond-sRGB.frag
    Including buffershader: /home/claude/code/code.mathr.co.uk/raymond/include/Raymond-sRGB-Buffer.frag
    Parse: /home/claude/code/code.mathr.co.uk/raymond/include/Raymond-sRGB-Buffer.frag
    Including file: /home/claude/code/code.mathr.co.uk/raymond/include/Raymond.frag
    Including file: /home/claude/opt/fragm/Fragmentarium-2.5.0/Examples/Include/Complex.frag
    Including file: /home/claude/code/code.mathr.co.uk/raymond/include/Raymond-Hash.frag
    Including file: /home/claude/code/code.mathr.co.uk/raymond/include/Raymond-Defs.frag
    Including file: /home/claude/code/code.mathr.co.uk/raymond/include/Raymond-Core.frag
    Including file: /home/claude/code/code.mathr.co.uk/raymond/include/Raymond-Random.frag
    Including file: /home/claude/code/code.mathr.co.uk/raymond/include/Raymond-Halton.frag
    Including file: /home/claude/code/code.mathr.co.uk/raymond/include/Raymond-Quaternion.frag
    Including file: /home/claude/code/code.mathr.co.uk/raymond/include/Raymond-Transform.frag
    Including file: /home/claude/code/code.mathr.co.uk/raymond/include/Raymond-Surface.frag
    Including file: /home/claude/code/code.mathr.co.uk/raymond/include/Raymond-Fractal.frag
    Including file: /home/claude/code/code.mathr.co.uk/raymond/include/Raymond-Material.frag
    Including file: /home/claude/code/code.mathr.co.uk/raymond/include/Raymond-D65.frag
    Including file: /home/claude/code/code.mathr.co.uk/raymond/include/Raymond-Glass.frag
    Including file: /home/claude/code/code.mathr.co.uk/raymond/include/Raymond-Quartz.frag
    Including file: /home/claude/code/code.mathr.co.uk/raymond/include/Raymond-Water.frag
    Including file: /home/claude/code/code.mathr.co.uk/raymond/include/Raymond-Observer.frag
    Including file: /home/claude/code/code.mathr.co.uk/raymond/include/Raymond-FP4Plus.frag
    Including file: /home/claude/code/code.mathr.co.uk/raymond/include/Raymond-Screen.frag
    Including file: /home/claude/code/code.mathr.co.uk/raymond/include/Raymond-SkyBox.frag
    Including file: /home/claude/code/code.mathr.co.uk/raymond/include/Raymond-Trace.frag
    Including file: /home/claude/code/code.mathr.co.uk/raymond/include/Raymond-Pinhole.frag
    Raymond - a physics-inspired ray tracer (C) 2018 Claude Heiland-Allen (License GPL3+)
    Tried path: /home/claude/opt/fragm/Fragmentarium-2.5.0/raymond/examples
    Tried path: /home/claude/opt/fragm/Fragmentarium-2.5.0/Examples/Include
    Tried path: /home/claude/code/code.mathr.co.uk/raymond/include
    Could not resolve path for file: 
    Tried path: /home/claude/opt/fragm/Fragmentarium-2.5.0/raymond/examples
    Tried path: /home/claude/opt/fragm/Fragmentarium-2.5.0/Examples/Include
    Tried path: /home/claude/code/code.mathr.co.uk/raymond/include
    Could not resolve path for file: 
    Setting texture to: 
    Camera: Use W/S to fly. 1/3 adjusts speed. Q/E rolls. Click on 3D window for key focus. See Help Menu for more.
    Created front and back buffers as RGBA32F
    Maximum texture size: 16384x16384
    Not a valid texture: 
    Compiled script in 37 ms.

**Comment by 3Dickulus** [comment]
ok adjusted the include path, seems to work

**Comment by 3Dickulus** [comment]
QFSFileEngine::open: No file name specified
QFSFileEngine::open: No file name specified

when declaring uniform sampler2D Background; file[] it needs a file

when I add a filename in Raymond-SkyBox.frag it seems to render fine when called from cmdline with examples/SkyBox.frag and switches textures when applying the other presets

**Comment by claudeha** [comment]
yes it switches textures fine the first couple of times but gets stuck (can't switch back to previous image)

**Comment by 3Dickulus** [comment]
lines 551 - 559 check the texture cache first, this seems broken :(

**Comment by 3Dickulus** [comment]
ok I think I found it, the texture cache ( the old one from the last "build" ) needs to be cleared when initializeFragment() is called, for the same reason that clearTextures(); is called when tab is switched, to freshen the cache.

so, try adding clearTextures(); as the first line in MainWindow::initializeFragment()
works as expected here :D

**Comment by 3Dickulus** [comment]
The problems with textures goes way back and I should dig into the flow of the "initializeFragment -> build variable editor pages -> cache textures -> set uniforms" process. Currently have to initializeFragment a few time to make everything stick.

**Comment by 3Dickulus** [comment]
pushed a fix for this issue, still not the way I think it should be but it seems to do the job, no clearing cache needed, seems to use the cached texture filenames properly, still requires initializeFragment() to be connected twice to the build button.

let me know if this works on your setup :)

**Comment by claudeha** [comment]
Just tried current master, switching back and forth between Berlin/Paris presets works fine now, thanks!

    407f6a3 (HEAD -> master, tag: Fragmentarium-2.5_162-034125, 3Dickulus/master) Refinement for issue #27 fix
