### ISSUE TITLE
How do you build it?

### ISSUE THREAD

**Issue by rotten** [3Dickulus/FragM#3]
The file system layout does not reveal any obvious standard build method.

When I try this, it doesn't work:
```

$  cd Fragmentarium-Source/
$  qmake
WARNING: Failure to find: SyntopiaCore/Misc/ColorUtils.cpp
WARNING: Failure to find: SyntopiaCore/Misc/ColorUtils.h

```

(I'm trying this on a linux system.)

**Comment by 3Dickulus** [comment]
Thank you for bringing this up, I don't use qmake or qcreator for development so this slipped by me...
in the Fragmentarium.pro file you can safely remove the 2 lines
```
$$PWD/./SyntopiaCore/Misc/ColorUtils.h \
$$PWD/./SyntopiaCore/Misc/ColorUtils.cpp \
```
and if you are **not** building with OpenEXR you can also remove these lines or adjust them to point at the OpenEXR libraries and includes

```
LIBS += -L$$PWD/../OpenEXR/lib/ -lIlmImf-2_1 -lHalf -lIex-2_1 -lIexMath-2_1 -lImath-2_1 -lIlmThread-2_1

INCLUDEPATH += $$PWD/../OpenEXR/include/OpenEXR
DEPENDPATH += $$PWD/../OpenEXR/lib
PRE_TARGETDEPS += $$PWD/../OpenEXR/lib/libIlmImf-2_1.a $$PWD/../OpenEXR/lib/libHalf.a $$PWD/../OpenEXR/lib/libIex-2_1.a  $$PWD/../OpenEXR/lib/libIexMath-2_1.a $$PWD/../OpenEXR/lib/libIlmThread-2_1.a $$PWD/../OpenEXR/lib/libImath-2_1.a
```

these lines expect OpenEXR libs compiled from sources in the top level folder, FragM/OpenEXR

I would, however, recommend you use CMake-gui, it will allow you to set compile time variables like lib paths and other options before generating the makefile.

Install CMake and CMake-gui for your distribution, it should be available in your "packages tree"
then
```
$  cd Fragmentarium-Source/
$ mkdir build
$ cd build
$ cmake-gui ..
```
don't forget the dotdot, generate using native toolchain, set
NVIDIAGL4PLUS = ON if you have a gfx card that supports GL => 4.0 (required for FragM 2.0 features)
USE_OPEN_EXR = ON if you have the OpenEXR devel package installed, highly recommended, this will let you create tiled images larger than 8192x8192

summary: Fragmentarium.pro + qmake requires a bit of tweaking to match your setup
                 CMake expects system installed dev packages

alternative: try the RPM built on 64bit SuSE Leap42.2 http://www.digilanti.org/fragmentarium/Fragmentarium-2.0.0-Linux.rpm

**Comment by 3Dickulus** [comment]
I have updated the Fragmentarium.pro file
It should create a makefile and compile a working executable if OpenEXR plus dev package is installed
