### ISSUE TITLE
illegal use of reserved word `long' in Complex.frag

### ISSUE THREAD

**Issue by claudeha** [3Dickulus/FragM#31]
GLSL does not have `long` or `longBitsToDouble`, or at least the implementation in Mesa with 4.5COMPAT version override doesn't.

    Could not create fragment shader: 0:1355(2): error: illegal use of reserved word `long'
    0:1355(2): error: syntax error, unexpected ERROR_TOK

fix is simple: delete

    double pow(double a, double b) {
        long tmp = long(9076650*(a-1) / (a+1+4*(sqrt(a)))*b + 1072632447);
        return longBitsToDouble(tmp << 32);
    }

add

    double pow(double a, double b) {
        return exp(log(a) * b);
    }

**Comment by 3Dickulus** [comment]
#extension GL_ARB_shader_bit_encoding : enable

found in MathUtils.frag ??? I always include MathUtils.frag before Complex.frag so haven't noticed this.

**Comment by claudeha** [comment]
#version 450 compatibility
    #extension GL_ARB_shader_bit_encoding : enable
    
    #include "2D.frag"
    
    double pow(double a, double b) {
        long tmp = long(9076650*(a-1) / (a+1+4*(sqrt(a)))*b + 1072632447);
        return longBitsToDouble(tmp << 32);
    }
    
    vec3 color(vec2 p) 
    {
      return vec3(1.0);
    }

gives the same error

**Comment by claudeha** [comment]
http://docs.gl/ doesn't list anything with `long`, while it has http://docs.gl/sl4/floatBitsToInt

**Comment by claudeha** [comment]
http://docs.gl/sl4/packDouble2x32 is what we need afaict

**Comment by 3Dickulus** [comment]
so the replacement pow function you suggest above has the same result ? accuracy ?

I don't have the problem with nVidia native driver

I find at https://www.khronos.org/registry/OpenGL/extensions/NV/NV_gpu_shader5.txt

```
                                Can be implicitly
        Type of expression        converted to
        --------------------    -----------------------------------------
        int                     uint, int64_t, uint64_t, float, double(*)
        ivec2                   uvec2, i64vec2, u64vec2, vec2, dvec2(*)
        ivec3                   uvec3, i64vec3, u64vec3, vec3, dvec3(*)
        ivec4                   uvec4, i64vec4, u64vec4, vec4, dvec4(*)

        int8_t   int16_t        int, int64_t, uint, uint64_t, float, double(*)
        i8vec2   i16vec2        ivec2, i64vec2, uvec2, u64vec2, vec2, dvec2(*)
        i8vec3   i16vec3        ivec3, i64vec3, uvec3, u64vec3, vec3, dvec3(*)
        i8vec4   i16vec4        ivec4, i64vec4, uvec4, u64vec4, vec4, dvec4(*)

        int64_t                 uint64_t, double(*)
        i64vec2                 u64vec2, dvec2(*)
        i64vec3                 u64vec3, dvec3(*)
        i64vec4                 u64vec4, dvec4(*)

        uint                    uint64_t, float, double(*)
        uvec2                   u64vec2, vec2, dvec2(*)
        uvec3                   u64vec3, vec3, dvec3(*)
        uvec4                   u64vec4, vec4, dvec4(*)

        uint8_t  uint16_t       uint, uint64_t, float, double(*)
        u8vec2   u16vec2        uvec2, u64vec2, vec2, dvec2(*)
        u8vec3   i16vec3        uvec3, u64vec3, vec3, dvec3(*)
        u8vec4   i16vec4        uvec4, u64vec4, vec4, dvec4(*)

        uint64_t                double(*)
        u64vec2                 dvec2(*)
        u64vec3                 dvec3(*)
        u64vec4                 dvec4(*)

        float                   double(*)
        vec2                    dvec2(*)
        vec3                    dvec3(*)
        vec4                    dvec4(*)

        float16_t               float, double(*)
        f16vec2                 vec2, dvec2(*)
        f16vec3                 vec3, dvec3(*)
        f16vec4                 vec4, dvec4(*)

        (*) if ARB_gpu_shader_fp64 is supported

    (Note:  Expressions of type "int32_t", "uint32_t", "float32_t", and
    "float64_t" are treated as identical to those of type "int", "uint",
    "float", and "double", respectively.  Implicit conversions to and from
    these explicitly-sized types are allowed whenever conversions involving
    the equivalent base type are allowed.)
```

can we use 

`#define long int64_t`

???

**Comment by 3Dickulus** [comment]
oops not closed :-/

**Comment by claudeha** [comment]
This might work (untested):

    double pow(double a, double b) {
        // converting to int instead of long should keep the least significant 32 bits
        int tmp = int(9076650*(a-1) / (a+1+4*(sqrt(a)))*b + 1072632447);
        // tmp << 32 as long would fill the least significant bits with 0 and move the previous lsb to msb, little-endian gives:
        return packDouble2x32(uvec2(0, tmp));
    }

I'm suspicious of this function, `exp(log(a)*b)` should be accurate if `exp` and `log` are? (but see other ticket, they may be off...)

**Comment by claudeha** [comment]
I'm informed by IRC denizens that GLSL spec says double->int when out of range is undefined (not lsb as I would have hoped).  There may be a way to rescue it using wrapping as double, but seems more trouble than it's worth...

**Comment by claudeha** [comment]
the magic number version is not very accurate (53 - 32 = 21 bits of mantissa, less than single precision float).  not worth the pain involved imo.

IRC suggests mod(..., 2^32) as a workaround, maybe should be 2^31 in case of sign (but it doesn't work for `<0` because `sqrt()`, perhaps `uint` would be better? but that might clobber `double` sign bit...)

**Comment by 3Dickulus** [comment]
... if exp() and log() are ok then `exp(log(a)*b)` works :)

**Comment by 3Dickulus** [comment]
when I use `long test = 0;` and use `test` in frag code so it doesn't get optimized out, it compiles with no complaints ??? must be the GL_NV extensions that allow this and `longBitsToDouble()`

have you tried adding
```
#extension GL_ARB_shader_bit_encoding : enable
#extension GL_EXT_gpu_shader4 : enable
#extension GL_ARB_gpu_shader5 : enable
```
 they only get added to frag from MathUtils.frag if WANG_HASH is defined.

**Comment by 3Dickulus** [comment]
with the changes you mention to `exp(double x)` it seems to be rendering nicely so don't need the `pow()` function that uses longBits, nice :) will have to update the

**Comment by 3Dickulus** [comment]
more accurate double pow() function presented in #36 using int64_t

**Comment by claudeha** [comment]
Sorry, my desktop had a hardware failure.  Old laptop doesn't do `double` at all, so I can't test this stuff until I get a replacement motherboard.

**Comment by 3Dickulus** [comment]
closed: use **int64_t** instead of **long**
