### ISSUE TITLE
clamping variable message has additional 1 in variable name

### ISSUE THREAD

**Issue by claudeha** [3Dickulus/FragM#32]
Says

    Clamping Zoom1 to min/max range!

when my variable is

    Zoom

(thanks for this warning!)

may be `double` related?

**Comment by 3Dickulus** [comment]
all variable names are appended internally to differentiate.
the parts of vec3 varname would be refered to as varname1=x varname2=y varname3=z so you know what part of a variable is being referenced, a float var is always appended with 1, this also helps when applying an easing curve to just one part of a vec2 vec3 or vec4

this is "normal behavior" for FragM
