### ISSUE TITLE
logarithmic slider support (feature request)

### ISSUE THREAD

**Issue by claudeha** [3Dickulus/FragM#33]
When I edit `Progressive2D.frag` to set `Zoom` slider max to `1e13` (for `double`) the slider becomes a bit useless as it is linear.  A logarithmic mode for sliders would be great (save having to do per-pixel `log` in GLSL and keeps the camera logic logical).  Would require both endpoints to have the same sign (no zero).

**Comment by 3Dickulus** [comment]
requires rewriting FloatWidget(s)

**Comment by 3Dickulus** [comment]
...and adding slider type `linear`, default, and `logarithmic`, optional, to the parser, this will probably affect easing curves when applied to a slider.

**Comment by 3Dickulus** [comment]
re:useless slider
with such a large number the slider step multiplier needs to be adjusted, right click on the Zoom slider and enter 1000 or 10000, that will make the arrow keys and page-up/down keys working.
The step value is automagicaly calculated for all other sliders but gets set to 1 for Zoom slider in 2D thus rendering it useless... investigating...

**Comment by claudeha** [comment]
step multiplier could be relative to current value, eg 1% for fine adjustment, 10% for slightly coarser, etc.

implemented by `*= 1.01` and `/= 1.01` for up and down

**Comment by 3Dickulus** [comment]
step multiplier is controled by Shift+wheel but doesn't work in the double test frags, only in standard float frags. not sure why? the code mechanism should not be affected by float/double type frags as it's all in the C++ code not GLSL, hmmm, something else to investigate... fixed?

I have a beta logarithmic slider version, enabled via **log_** prefix on slider name, but only works halfway, by the time the slider is dragged to just over half the spinner hits max.
just pushed,
using...
#define USE_DOUBLE
#include "MathUtils.frag"
#include "Complex.frag"
#include "Progressive2D-4.frag"

**Comment by 3Dickulus** [comment]
look at ThirdParty/qdoublerangeslider.cpp there is some settings and calculations for logarithmic range sliders but I think it may have been left in an unfinished state, I don't recall exactly where I found that code, an example somewhere? maybe can subclass QSlider and add the log bits?

**Comment by claudeha** [comment]
Working on it...  approach is to add a logarithmic slider bool flag to `ComboSlider`, and plumb it through from the parser for `float vec2 vec3 vec4` `slider`.  Default will remain Linear, syntax will be like:

```
uniform float Zoom; slider[1e-6,1,1e16 Logarithmic NotLockable
```

Seems cleaner than having to modify uniform names.
