### ISSUE TITLE
CMake Error at cmake_install.cmake:82 (file):   file INSTALL cannot find   

### ISSUE THREAD

**Issue by adammaj1** [3Dickulus/FragM#4]
Hi,

I have gone thru steps of installations : 
https://en.wikibooks.org/wiki/Fractals/fragmentarium#Build_3
until : 
-- Installing: /home/a/FragM/Fragmentarium/EULA_de.txt
-- Installing: /home/a/FragM/Fragmentarium/EULA_ru.txt
-- Installing: /home/a/FragM/Fragmentarium/EULA_nl.txt
CMake Error at cmake_install.cmake:82 (file):
  file INSTALL cannot find
  "/home/a/FragM/Fragmentarium-Source/build/Fragmentarium_de.qm".

Any help ?
---------
In log file I did not found any errors

**Comment by adammaj1** [comment]
[CMakeOutput.log.txt](https://github.com/3Dickulus/FragM/files/1272181/CMakeOutput.log.txt)

**Comment by 3Dickulus** [comment]
line 163 in the CMakeLists.tx file should be...

          file (GLOB TRANSLATIONS **Translations/***.ts)

**Comment by adammaj1** [comment]
OK. I have changed it and 
CMake Error at cmake_install.cmake:82 (file):
  file INSTALL cannot find
  "/home/a/FragM/Fragmentarium-Source/build/Fragmentarium_de.qm".


Makefile:137: polecenia dla obiektu 'install' nie powiodły się
make: *** [install] Błąd 1


[CMakeLists.txt](https://github.com/3Dickulus/FragM/files/1272462/CMakeLists.txt)

**Comment by adammaj1** [comment]
after some tries 
a@zelman:~/FragM/Fragmentarium$ ./Fragmentarium-2.0.b
./Fragmentarium-2.0.b: /usr/lib/x86_64-linux-gnu/libQt5Script.so.5: version `Qt_5' not found (required by ./Fragmentarium-2.0.b)
./Fragmentarium-2.0.b: /usr/lib/x86_64-linux-gnu/libQt5OpenGL.so.5: version `Qt_5' not found (required by ./Fragmentarium-2.0.b)
./Fragmentarium-2.0.b: /usr/lib/x86_64-linux-gnu/libQt5Xml.so.5: version `Qt_5' not found (required by ./Fragmentarium-2.0.b)
./Fragmentarium-2.0.b: /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5: version `Qt_5' not found (required by ./Fragmentarium-2.0.b)
./Fragmentarium-2.0.b: /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5: version `Qt_5' not found (required by ./Fragmentarium-2.0.b)
./Fragmentarium-2.0.b: /usr/lib/x86_64-linux-gnu/libQt5Core.so.5: version `Qt_5.7' not found (required by ./Fragmentarium-2.0.b)
./Fragmentarium-2.0.b: /usr/lib/x86_64-linux-gnu/libQt5Core.so.5: version `Qt_5' not found (required by ./Fragmentarium-2.0.b)

and inside program

Parse: /home/a/FragM/Fragmentarium-Source/Examples/Historical 3D Fractals/Mandelbulb.frag
Tried path: /home/a/FragM/Fragmentarium-Source/Examples/Historical 3D Fractals/MathUtils.frag
Tried path: /home/a/FragM/Fragmentarium-Source/build/Examples/Include/MathUtils.frag
Could not resolve path for file: MathUtils.frag
Tried path: /home/a/FragM/Fragmentarium-Source/Examples/Historical 3D Fractals/DE-Raytracer.frag
Tried path: /home/a/FragM/Fragmentarium-Source/build/Examples/Include/DE-Raytracer.frag
Could not resolve path for file: DE-Raytracer.frag
Mandelbulb Distance Estimator
Camera: Click on 2D window for key focus. See Help Menu for more.
Created front and back buffers as 
Maximum texture size: 16384x16384
No vertex shader found!
Could not create vertex shader: 
Could not find Center interface widget
Could not find Zoom interface widget
Failed to compile script (5 ms).

**Comment by 3Dickulus** [comment]
I tested the change and it seemed to work fine here. SuSE Leap 42.2
On this system Qt installs libraries in  /usr/lib64/
I see all of the *qm files in my build folder

**Comment by 3Dickulus** [comment]
compiled on travis-cl.org using ubuntu trusty

```
sudo add-apt-repository -y ppa:ubuntu-sdk-team/ppa
sudo apt-get update -qq
sudo apt-get -qq install g++-4.8 libc6-i386
sudo apt-add-repository -y ppa:beineri/opt-qt571-trusty
sudo apt-get -qq update
sudo apt-get -qq install qtcreator-latest
source /opt/qt57/bin/qt57-env.sh
mkdir Fragmentarium-Source/build
cd Fragmentarium-Source/build
cmake -DNVIDIAGL4PLUS=ON -DUSE_OPEN_EXR=ON ..
make
```
will be making binaries available as soon as I get travis figured out
