### ISSUE TITLE
build fails with errors in loadEXRTexture

### ISSUE THREAD

**Issue by claudeha** [3Dickulus/FragM#42]
claude@latte:~/code/github.com/3Dickulus/FragM/Fragmentarium-Source/build$ make -k
    [  2%] Automatic MOC and UIC for target Fragmentarium-2.5.0
    [  2%] Built target Fragmentarium-2.5.0_autogen
    [  5%] Building CXX object CMakeFiles/Fragmentarium-2.5.0.dir/Fragmentarium/GUI/DisplayWidget.cpp.o
    /home/claude/code/github.com/3Dickulus/FragM/Fragmentarium-Source/Fragmentarium/GUI/DisplayWidget.cpp: In member function ‘bool Fragmentarium::GUI::DisplayWidget::loadEXRTexture(QString, GLenum, GLuint)’:
    /home/claude/code/github.com/3Dickulus/FragM/Fragmentarium-Source/Fragmentarium/GUI/DisplayWidget.cpp:641:5: error: ‘RgbaInputFile’ was not declared in this scope
         RgbaInputFile file ( texturePath.toLatin1().data() );
         ^~~~~~~~~~~~~
    /home/claude/code/github.com/3Dickulus/FragM/Fragmentarium-Source/Fragmentarium/GUI/DisplayWidget.cpp:641:5: note: suggested alternative: ‘outputFile’
         RgbaInputFile file ( texturePath.toLatin1().data() );
         ^~~~~~~~~~~~~
         outputFile
    /home/claude/code/github.com/3Dickulus/FragM/Fragmentarium-Source/Fragmentarium/GUI/DisplayWidget.cpp:642:5: error: ‘Box2i’ was not declared in this scope
         Box2i dw = file.dataWindow();
         ^~~~~
    /home/claude/code/github.com/3Dickulus/FragM/Fragmentarium-Source/Fragmentarium/GUI/DisplayWidget.cpp:644:10: error: ‘file’ was not declared in this scope
         if ( file.isComplete() ) {
              ^~~~
    /home/claude/code/github.com/3Dickulus/FragM/Fragmentarium-Source/Fragmentarium/GUI/DisplayWidget.cpp:644:10: note: suggested alternative: ‘Tiled’
         if ( file.isComplete() ) {
              ^~~~
              Tiled
    /home/claude/code/github.com/3Dickulus/FragM/Fragmentarium-Source/Fragmentarium/GUI/DisplayWidget.cpp:646:18: error: ‘dw’ was not declared in this scope
             int w  = dw.max.x - dw.min.x + 1;
                      ^~
    /home/claude/code/github.com/3Dickulus/FragM/Fragmentarium-Source/Fragmentarium/GUI/DisplayWidget.cpp:646:18: note: suggested alternative: ‘w’
             int w  = dw.max.x - dw.min.x + 1;
                      ^~
                      w
    /home/claude/code/github.com/3Dickulus/FragM/Fragmentarium-Source/Fragmentarium/GUI/DisplayWidget.cpp:658:9: error: ‘Array2D’ was not declared in this scope
             Array2D<Rgba>pixels ( w, 1 );
             ^~~~~~~
    /home/claude/code/github.com/3Dickulus/FragM/Fragmentarium-Source/Fragmentarium/GUI/DisplayWidget.cpp:658:17: error: ‘Rgba’ was not declared in this scope
             Array2D<Rgba>pixels ( w, 1 );
                     ^~~~
    /home/claude/code/github.com/3Dickulus/FragM/Fragmentarium-Source/Fragmentarium/GUI/DisplayWidget.cpp:658:17: note: suggested alternative:
    In file included from /usr/include/x86_64-linux-gnu/qt5/QtOpenGL/QtOpenGL:5,
                     from /home/claude/code/github.com/3Dickulus/FragM/Fragmentarium-Source/ThirdPartyCode/QtSpline.h:46,
                     from /home/claude/code/github.com/3Dickulus/FragM/Fragmentarium-Source/Fragmentarium/GUI/DisplayWidget.h:51,
                     from /home/claude/code/github.com/3Dickulus/FragM/Fragmentarium-Source/Fragmentarium/GUI/DisplayWidget.cpp:14:
    /usr/include/x86_64-linux-gnu/qt5/QtOpenGL/qgl.h:85:9: note:   ‘Rgba’
             Rgba                    = 0x0004,
             ^~~~
    /home/claude/code/github.com/3Dickulus/FragM/Fragmentarium-Source/Fragmentarium/GUI/DisplayWidget.cpp:658:22: error: ‘pixels’ was not declared in this scope
             Array2D<Rgba>pixels ( w, 1 );
                          ^~~~~~
    /home/claude/code/github.com/3Dickulus/FragM/Fragmentarium-Source/Fragmentarium/GUI/DisplayWidget.cpp:658:22: note: suggested alternative: ‘tiles’
             Array2D<Rgba>pixels ( w, 1 );
                          ^~~~~~
                          tiles
    make[2]: *** [CMakeFiles/Fragmentarium-2.5.0.dir/build.make:182: CMakeFiles/Fragmentarium-2.5.0.dir/Fragmentarium/GUI/DisplayWidget.cpp.o] Error 1
    make[2]: Target 'CMakeFiles/Fragmentarium-2.5.0.dir/build' not remade because of errors.
    make[1]: *** [CMakeFiles/Makefile2:73: CMakeFiles/Fragmentarium-2.5.0.dir/all] Error 2
    make[1]: Target 'all' not remade because of errors.
    make: *** [Makefile:130: all] Error 2
    make: Target 'default_target' not remade because of errors.
    $

**Comment by claudeha** [comment]
I have this OpenEXR version on Debian Buster:

    claude@latte:~$ apt-cache policy libopenexr-dev
    libopenexr-dev:
      Installed: 2.2.1-4.1
      Candidate: 2.2.1-4.1
      Version table:
     *** 2.2.1-4.1 990
            990 http://ftp.uk.debian.org/debian buster/main amd64 Packages
            500 http://http.debian.net/debian unstable/main amd64 Packages
            100 /var/lib/dpkg/status

**Comment by claudeha** [comment]
Same errors when disabling OpenEXR:

    claude@latte:~/code/github.com/3Dickulus/FragM/Fragmentarium-Source/build$ grep USE_OPEN_EXR CMakeCache.txt 
    USE_OPEN_EXR:BOOL=OFF

**Comment by 3Dickulus** [comment]
already there around line 820 in DisplayWidget.cpp
```
#ifdef USE_OPEN_EXR
                    else if (texturePath.endsWith(".exr", Qt::CaseInsensitive)) { // is EXR format image ?
                        loaded = loadEXRTexture(texturePath, type, textureID);
                    }
#endif
```
Qt successfully loads EXR format images but does some conversion en-route so we end up with RGBA8 internally instead of RGBA32

in the very near future including OpenEXR will not be optional, it will be included and enabled by default

**Comment by claudeha** [comment]
yes already there at the use site, but not the definition site
