### ISSUE TITLE
bad scroll wheel behaviour for 2d camera

### ISSUE THREAD

**Issue by claudeha** [3Dickulus/FragM#45]
Should zoom about cursor position instead of what it does now (which I find very frustrating).  Fix forthcoming...

**Comment by 3Dickulus** [comment]
Not sure what you mean, it does zoom about mouse pointer with wheel.

**Comment by claudeha** [comment]
not here without my fix.  with my version the image point under the cursor remains fixed in place when wheel zooming, with yours it zooms about some other point offset from the cursor

**Comment by 3Dickulus** [comment]
will study your patch, do a little research, and try to figure out why this is the case.
I assume you are using the latest sources 2.5.0-190802

**Comment by claudeha** [comment]
freshly updated from git this afternoon

**Comment by 3Dickulus** [comment]
ok looking into it... on mine the point under the cursor moves toward the center as I zoom so when pointer is in upper left quadrant zooming will take the view in that direction.

**Comment by 3Dickulus** [comment]
> and try to figure out why this is the case.

? that was in reference to GL stuff :)
