### ISSUE TITLE
line pragmas break on Mesa

### ISSUE THREAD

**Issue by claudeha** [3Dickulus/FragM#52]
something with the line pragmas?

     Could not create fragment shader: 0:3(89): preprocessor error: syntax error, unexpected OTHER, expecting INTEGER or INTEGER_STRING or NEWLINE

preprocessed frag has a line pragma on line 3...

    // Write fragment code here...
    // #donotrun
    #line 1 "/home/claude/opt/fragm/glm/Fragmentarium-2.5.0/Examples/Include/MathUtils.frag"
    #ifdef WANG_HASH
    ...

>  The #line directive does not support source files as in C.

<https://www.khronos.org/opengl/wiki/Core_Language_(GLSL)#.23line_directive> says you can only specify a source string number, not a filename or other string :(

**Comment by 3Dickulus** [comment]
huh :-/

I get log lines like this...
`/home/Fragmentarium/test.frag(130) : warning C7011: implicit cast from "int" to "float"`

**Comment by 3Dickulus** [comment]
quote from https://www.khronos.org/opengl/wiki/Core_Language_(GLSL)#.23line_directive

> #line directive
> 
> The #line directive allows you to change the current __FILE__ and __LINE__ values

**Comment by claudeha** [comment]
I already quoted a bit from there.  It only supports string numbers, not filenames, at least per the spec, which Mesa adheres to (NVIDIA is too lenient, leading to breakage elsewhere...).

I have some patches that print out a filename map before error messages with string numbers:

    0 -> Unnamed
    1 -> /home/claude/opt/fragm/glm/Fragmentarium-2.5.0/Examples/Include/MathUtils.frag
    2 -> /home/claude/opt/fragm/glm/Fragmentarium-2.5.0/Examples/Include/DE-Raytracer.frag
    3 -> /home/claude/opt/fragm/glm/Fragmentarium-2.5.0/Examples/Include/3D.frag
    Could not create fragment shader: 0:6(40): error: syntax error, unexpected FLOATCONSTANT, expecting ')' or ','

So this error occured in an `Unnamed` (unsaved) frag.  Fixing it and adding an error in `DE-Raytracer.frag` gives

    0 -> Unnamed
    1 -> /home/claude/opt/fragm/glm/Fragmentarium-2.5.0/Examples/Include/MathUtils.frag
    2 -> /home/claude/opt/fragm/glm/Fragmentarium-2.5.0/Examples/Include/DE-Raytracer.frag
    3 -> /home/claude/opt/fragm/glm/Fragmentarium-2.5.0/Examples/Include/3D.frag
    Could not create fragment shader: 2:15(1): error: syntax error, unexpected NEW_IDENTIFIER, expecting $end

which I hope is better than nothing (or the total breakage from using filenames).

**Comment by 3Dickulus** [comment]
quote from https://www.khronos.org/opengl/wiki/Core_Language_(GLSL)#.23line_directive

> #line directive
> The #line directive allows you to change the current __FILE__ and __LINE__ values

a string is a string is a string so shouldn't matter if it's numbers or letters (but apparently it does)

If you are using nVidia gfx card I highly recomend using the nVidia driver, the installer builds a kernel module from source with a bit of proprietary stuff thrown in, using any other driver will not let you enjoy the full power of the gfx card and imho will always have problems. This is why I'm not really actively supporting anything other than manufacturers officially released drivers or hardware that doesn't support at least GL 4.0

**Comment by claudeha** [comment]
full quote of that section, as you didn't pay attention to the part I quoted already:

> #line directive

> The #line directive allows you to change the current __FILE__ and __LINE__ values, and is different from C. It has the forms:

> #line line

> #line line source-string-number

> The line after the #line directive in the source will be set to the give line number. For example, if you have "#line 4" on one line and "error" on the next, then "error" will be on line 4 if it is an error. The #line directive **does not support source files** as in C.

(my emphasis)

**Comment by 3Dickulus** [comment]
nVidia driver/compiler has no problems with this (GL>4)

I have a working version that uses numbers as index into filename list and puts the correct filename in the log, should work for AMD too.

**Comment by claudeha** [comment]
nVidia driver/compiler is known to accept out-of-spec input, which leads to issues everywhere else.

looking forward to test your fixes!
