### ISSUE TITLE
debug vs release builds problematic

### ISSUE THREAD

**Issue by claudeha** [3Dickulus/FragM#57]
I think <https://github.com/3Dickulus/FragM/blob/aca1376f5757238139086f22e187116d34ad16fb/Fragmentarium-Source/CMakeLists.txt#L22> prevents setting arguments on the command line like

    cmake .. -DCMAKE_BUILD_TYPE=Debug

which makes debugging harder than necessary (have to edit the file)

**Comment by 3Dickulus** [comment]
use cmake-gui

**Comment by claudeha** [comment]
ok

**Comment by 3Dickulus** [comment]
cmake-gui is one of my favorite tools :) lets you adjust vars before creating the makefile, works on windows too
