### ISSUE TITLE
DE-Raytracer-Slicer.frag does not work

### ISSUE THREAD

**Issue by claudeha** [3Dickulus/FragM#68]
https://github.com/3Dickulus/FragM/blob/b2942c2ed550a59a6f6df15955e1a3c66c9d06c7/Fragmentarium-Source/Examples/Include/DE-Raytracer-Slicer.frag#L56

```
error: fragment shader input `dirDx' has no matching output in the previous stage
error: fragment shader input `dirDy' has no matching output in the previous stage
```

I don't know what `dirDx` and `dirDy` are supposed to be, so I can't fix it sensibly.

**Comment by 3Dickulus** [comment]
![Mandelbulb-Slicer](https://user-images.githubusercontent.com/4978723/63481805-98672a80-c44b-11e9-9a3b-7042b8a9811e.png)
![Mandelbox - Dual Numbers DE - Slicer](https://user-images.githubusercontent.com/4978723/63481806-98ffc100-c44b-11e9-97e0-70a8b37df864.png)

no errors or warns at compile time ??? must be that sloppy nVidia GLSL parser >:-{

**Comment by claudeha** [comment]
Setting them to 0 gives something similar to your image:

```
varying vec3 from,dir;
const vec3 dirDx = vec3(0.0);
const vec3 dirDy = vec3(0.0);
```

But they probably should really be set to something proper in the vertex part?
This is where they are used, setting them to 0 will break the spotlight I think?

https://github.com/3Dickulus/FragM/blob/b2942c2ed550a59a6f6df15955e1a3c66c9d06c7/Fragmentarium-Source/Examples/Include/DE-Raytracer-Slicer.frag#L170-L172

**Comment by 3Dickulus** [comment]
> I don't know what dirDx and dirDy are supposed to be, so I can't fix it sensibly.

```
Examples/Benesi/Fast-RaytracerPaletteColorTest.frag:    dirDx = ps.x*Right*FOV;
Examples/Benesi/Fast-Raytracer-with-Palette.frag:       dirDx = ps.x*Right*FOV;
Examples/Include/DE-Raytracer-v0.9.1.frag:      dirDx = ps.x*Right*FOV;
Examples/Include/Fast-Raytracer.frag:   dirDx = ps.x*Right*FOV;
Examples/Include/Subblue-Raytracer.frag:        dirDx = ps.x*Right*FOV;
Examples/Kali's Creations/Treebroccoli.frag:    dirDx = ps.x*Right*FOV;
Examples/Kali's Creations/Xray_skifs.frag:      dirDx = ps.x*Right*FOV;
```

I've noticed renders seem a bit darker since applying all of the latest pushes and pulls.
Not sure if it's just my tired old eyes or if maybe something is up with the oddball var Gamma not getting set/used like it did before the buffershader variable handling mod ???

**Comment by 3Dickulus** [comment]
I note that in DE-Raytracer-v0.9.1.frag it's declared as ...
`varying vec3 dirDx; // out`
...in the vertex part and then...
`in vec3 from,dir,dirDx,dirDy;`
...in the fragment part, but none of the other files from Include folder that use it declare it like this they all call it varying ???

**Comment by claudeha** [comment]
`in`/`out` is the new name for `varying` (I guess with multiple shader stages it's more logical that way).  Shouldn't make a difference, `varying` might be more compatible with ancient GLSL versions but is deprecated in modern GLSL versions...

**Comment by 3Dickulus** [comment]
> `varying vec3 dirDx; // out`
> ...in the vertex part and then...
> `in vec3 from,dir,dirDx,dirDy;`
> ...in the fragment part

it's a leftover, vertex has **varying** and fragment has **in**, from when FragM would compile vertex and fragment under different GLSL versions, no #version statement in vertex code meant that vertex code was always compiled as GLSL 1.1 no matter what version was set by user frag

now FragM takes the #version line from the user frag and makes sure that all parts are compiled under the same version.

**Comment by 3Dickulus** [comment]
Closing because **Mandelbulb-Slicer.frag** and **Mandelbox - Dual Numbers DE - Slicer.frag** appear to render as expected in all tests.
