### ISSUE TITLE
currentFragmentName() unexpected behaviour

### ISSUE THREAD

**Issue by claudeha** [3Dickulus/FragM#69]
https://github.com/3Dickulus/FragM/blob/b2942c2ed550a59a6f6df15955e1a3c66c9d06c7/Fragmentarium-Source/Fragmentarium/GUI/MainWindow.h#L464-L471

It would be more intuitive if it kept all but the last part (which is probably `frag`) and rejoined them again with `.`, instead of just the first part.  Otherwise fragment filenames with more than one `.` get a probably-unexpected name, which could lead to data loss (wrong file overwritten).

**Comment by 3Dickulus** [comment]
absolutely, this was just my bruteforce hack to get things working, probably got distracted before finishing it. very likely to find a number of these :-]
