### ISSUE TITLE
GLSL compiler log file+line reporting not quite right

### ISSUE THREAD

**Issue by claudeha** [3Dickulus/FragM#71]
All of this on AMD RX 580 Mesa Debian Buster Linux with `master` branch as of ~10mins ago.

1. An error in BufferShader vertex part does not list filename and Open File context menu doesn't work, line number (6) is way off (error actually on line 12 of the .frag file):
    ```
    Could not create buffer vertex shader: 0:6(16): error: syntax error, unexpected NEW_IDENTIFIER, expecting ';' or '{'
    ```

2. An error in BufferShader fragment part does not list filename and Open File context menu doesn't work, line number (46) is correct.
    ```
    Could not create buffer fragment shader: 0:46(2): error: syntax error, unexpected BASIC_TYPE_TOK, expecting ',' or ';'
    ```

3. An error in an included Camera2D vertex part lists incorrect filename and Open File context menu doesn't work:
    ```
    /home/claude/code/code.mathr.co.uk/trudy/examples/MuET.frag :19(2): error: syntax error, unexpected BASIC_TYPE_TOK, expecting ',' or ';'
    ```
    the error is on lines 20-21 of file, so there is an off-by-one-or-two error
    ```
    /home/claude/code/code.mathr.co.uk/trudy/include/Trudy-Camera2D.frag
    ```

4. An error in an included Camera2D fragment part lists correct file name and line number, but Open File context menu does not work:
    ```
    /home/claude/code/code.mathr.co.uk/trudy/include/Trudy-Camera2D.frag :67(2): error: syntax error, unexpected BASIC_TYPE_TOK, expecting ',' or ';'
    ```

There seems to be an extra space after the filename before the numbers, maybe something is off there that breaks the Open File context menu?

**Comment by 3Dickulus** [comment]
It works very well here except for the vertex shader stuff, written against fragment in editor, adding the logic for vertex shouldn't be too hard

the lines in DisplayWidget::initFragmentShader() that call createErrorLineLog() should only be
617 "Could not create fragment shader: "
624 "Fragment shader compiled with warnings: "
637 "Fragment shader compiled with warnings: "

the others should only call WARN(message) + WARN(log) until I get the vertex part working

**Comment by 3Dickulus** [comment]
have accounted for #vertex code... almost there

**Comment by 3Dickulus** [comment]
I think this is as good as it gets, because of things like this, the compiler doesn't report the line that has a missing semi-colon, it tries to compile the next bit of valid code as continuation of the line and reports that line as the failure. I think this is a special case and for the most part the error line stuff is accurate (here on nVidia GTX 760)

**Comment by claudeha** [comment]
Looking much better! Great job :)

Log right-click open file still doesn't work for me though, and:

```
#info MuET.frag
#include "Trudy-sRGB.frag"
error here
#include "Trudy.frag"
```
reports the error as being in `Trudy-sRGB.frag` instead of `MuET.frag`.  Not a big deal though.

**Comment by 3Dickulus** [comment]
I have a couple more tweaks for this,
make "Open file" only show in the context menu when the line has a loadable file. done.
prevent #line directives from polluting Auto Save fragment code. done.

**Comment by claudeha** [comment]
I found out why my `Open file` context menu wasn't working - bad regexp, seems my AMD Mesa is different to your driver?

```
diff --git a/Fragmentarium-Source/SyntopiaCore/Logging/ListWidgetLogger.h b/Fragmentarium-Source/SyntopiaCore/Logging/ListWidgetLogger.h
index 937af4f..58f75b2 100644
--- a/Fragmentarium-Source/SyntopiaCore/Logging/ListWidgetLogger.h
+++ b/Fragmentarium-Source/SyntopiaCore/Logging/ListWidgetLogger.h
@@ -38,7 +38,7 @@ public:
 
         if ( choice == &openFileAction ) {
             QList<QListWidgetItem *> items = selectedItems();
-            QRegExp test ( "^(.*[.frag])\\s[(]([0-9]+)[)]" );
+            QRegExp test ( "^(.*[.frag])\\s[:]([0-9]+)[(]" );
             foreach ( QListWidgetItem *i, items ) {
                 if (test.indexIn(i->text()) != -1) {
                     // send signal to mainWindow to open this file and jump to line
```

**Comment by 3Dickulus** [comment]
haha, of course it is, have a fix for that in a few minutes...
( I've really got to learn how to use git better)

**Comment by 3Dickulus** [comment]
oops that leading `[:]` should be `.*`

`        QRegExp test ( "^(.*[.frag])\\s.*([0-9]+)[)]" );`

this will work for both nV and AMD

**Comment by 3Dickulus** [comment]
actually this just made me rethink a couple of things...
