### ISSUE TITLE
OpenEXR Bug

### ISSUE THREAD

**Issue by 3Dickulus** [3Dickulus/FragM#85]
**Description**
OpenEXR fails to compile using wine

**To Reproduce**
compile from source on windows

**Expected behavior**
compile successfully for windows

**Desktop**
Wine

**Additional context**
OpenEXR 2.2 2.3 fail to compile using wine

**Comment by claudeha** [comment]
openexr 2.4 has a new cmake build system that works for me in the context of crosscompiling from Linux to Windows

**Comment by 3Dickulus** [comment]
Will try to test this over this coming weekend...
test result: not needed
modified the mingw build bat OpenEXR 2.4 compiles successfully with these cmake options...
```
-DWIN32=ON
-DOPENEXR_DLL=ON 
-DUSE_ZLIB_WINAPI=ON 
-DBUILD_SHARED_LIBS=OFF 
-DCMAKE_BUILD_TYPE=Release 
-DCMAKE_INSTALL_PREFIX=C:\Fragmentarium-2.5.0-3Dickulus-full\OpenEXR 
-DZLIB_ROOT=C:\Fragmentarium-2.5.0-3Dickulus-full\zlib123-dll 
-DZLIB_INCLUDE_DIR=C:\Fragmentarium-2.5.0-3Dickulus-full\zlib123-dll\include 
-DZLIB_LIBRARY=C:\Fragmentarium-2.5.0-3Dickulus-full\zlib123-dll\zlib1.dll 
-DILMBASE_PACKAGE_PREFIX=C:\Fragmentarium-2.5.0-3Dickulus-full\OpenEXR -G "MinGW Makefiles" ..
```
