### ISSUE TITLE
2D Camera Zoom slider Logarithmic resets to Linear when changing tab to a 3D frag and back

### ISSUE THREAD

**Issue by claudeha** [3Dickulus/FragM#88]
**Describe the bug**
After changing tabs and back, the Camera 2D Zoom slider is no longer Logarithmic

**To Reproduce**
1. Build and install my latest pull request against master that makes 2D camera frags' Zoom sliders Logarithmic (or just add Logarithmic to your 2D camera frag's Zoom slider)
2. Close all tabs.
3. Open a 2D frag
4. See Zoom slider be Logarithmic
5. Open a 3D frag
6. Switch back to 2D frag
7. See Zoom slider not be Logarithmic any more

**Expected behavior**
Logarithmic Zoom slider stays Logarithmic

**Desktop (please complete the following information):**
 - OS: Debian Buster
 - Gfx card: AMD RX 580
 - Driver version: Vendor: X.Org Renderer: Radeon RX 580 Series (POLARIS10, DRM 3.27.0, 4.19.0-6-amd64, LLVM 7.0.1) GL Driver: 4.5 (Compatibility Profile) Mesa 18.3.6

**Comment by 3Dickulus** [comment]
In my test with the current Development branch logslider remains logslider when switching tabs ???

**Comment by 3Dickulus** [comment]
if Zoom slider is Logarithmic in Declaration and the Default preset does not specify a Logarithmic Zoom then the slider is set as such when the default preset is applied when the frag is initially loaded. (appears to be ignored?)

as it is now in Dev branch you can change from Logarithmic to Linear at will regardless of the state in the Declaration, just like Locking (with the exception of NotLockable and AlwayLocked)

I believe that this is the way it should be, requiring no changes to any frags, just add Logarithmic where you need/want it in Settings or Declaration. When writing a fresh frag and having a slider Declared as Logarithmic it will also be Logarithmic in the initial Default preset when it is created.

Every single frag was originally written without Logarithmic sliders so I see no real need to change any of them with the exception of the most recent 2D frags (DoubleTest and friends come to mind)

**Comment by 3Dickulus** [comment]
Logarithmic option is destined to be a little button next to the lock button at the end of the slider ;)

**Comment by claudeha** [comment]
I don't see the little button next to the lock button.  As it is now, setting a Logarithmic slider via preset strings is a world of pain...

**Comment by claudeha** [comment]
maybe even make sliders logarithmic automagically by default when end:start ratio < 0.01 or > 100 and 0 is not in the range?

**Comment by 3Dickulus** [comment]
the button isn't there yet but it's not a big deal to add it, tested a preliminary attempt and it worked but some other stuff needs doing before tweaking buttons, coming soon?

right now my priority is to get rid of legacy GL in DisplayWidget, this should not have any effect on the current frag base but eventually the frags will need to get updated too, or maybe keep all of the legacy frags along side of new versions.

Logarithmic as default? no. Automagic Logarithmic? no. must be a conscious decision by the coder with specific intent. We have no idea what a coder might be doing or trying to do. Logarithmic isn't that hard to type? Surely. I think it would be more annoying if one is trying to do something and the widget decides something else every time you try.

Automagic is not a bad idea if every person using FragM expects the same behavior or uses sliders in the exact same way. There is only one case where this may apply and that is only if all users assume this behavior as expected, that's for 2D Zoom slider, but again, we make the assumption that this is desired in all cases.

I am happy with the option being available and that it can be turned on/off at will... the button will be handy for that...

an idea for v3 ? RMB in text editor presents menu option "Add Widget" and a nice dialog pops up with available slider types and options ;)

**Comment by claudeha** [comment]
Logarithmic is hard to type when you have to add it to every preset of every user frag, instead of just once in the library frag.
