### ISSUE TITLE
towards loading arbitrary channels from EXR files

### ISSUE THREAD

**Issue by 3Dickulus** [3Dickulus/FragM#92]
**Working**
FragM generates RGBZ files and loads them properly.

**Other channels**
RGBAFLOAT and RGBZFLOAT working
RGBAHALF and RGBAUINT and arbitrary names to be implimented

**to consider**
VFX pipeline best practices? most widely used or popular format and channel layout?
![Screenshot_20191102_191025](https://user-images.githubusercontent.com/4978723/68079419-49703680-fda6-11e9-866c-372f8720f33c.png)

**Additional context**
keeping it simple

**Comment by 3Dickulus** [comment]
Loads any selected channels...

![Screenshot_20191103_011359](https://user-images.githubusercontent.com/4978723/68082402-578b7a80-fdd9-11e9-8643-7bf95cf76274.png)

**Comment by 3Dickulus** [comment]
working as intended, some cleanup and fine tuning required, channel string format semicolon separated list in preset after filename as in... `tex = test-channels.exr B;G;R`

**Comment by claudeha** [comment]
Some thoughts on the current status as of d79330c1283cab4a51c86f8296e49c939d953ee3 vs my old branch https://github.com/claudeha/FragM/tree/feature-exr-loader-flexible-channel-mapping (which is now way behind and conflicting with the Development branch...):

- The dropdown with checkboxes is a wrong user interface for this problem, because 1) you can select 0 or more than 4 channels, beyond the limit of OpenGL textures, and 2) you can't specify the order, which means you need hacks to swizzle in the frag.

    My 4x dropdown selection was much closer to being right, it would have just needed code to copy the channel data manually if necessary (for duplicated channels) after reading the EXR data (OpenEXR allows reading only one slice per requested channel name, which was causing some strange issues).

    I recall there being an issue with the 4x dropdowns taking up way too much space, not leaving enough for the filename, but that cosmetic issue could surely have been fixed too.

- Your user interface does allow me to select my non-standard channels and save them in presets (`DEX;DEY;N;NF`) but it seems they are not uploaded to the GPU, because the GLSL `texture()` call just returns (0,0,0,1).

- The texture cache does not seem to take into account selected channels.  I have to clear the texture cache between trying the non-standard channels and trying `B;G;R`, otherwise I get a blank image.  With the texture cached cleared, I can rebuild the frag and the texture displays ok (and as RGB instead of BGR, which is confusing).

    My branch handled this by storing the requested channels along with the filename as the key in the texture cache, this moreover allowed the same texture to be loaded several times with different channels.

- `*.exr` files are not listed under "Image Files" in the texture file browser, needs selecting "All Files" to show them

**Comment by claudeha** [comment]
https://github.com/claudeha/FragM/tree/feature-exr-loader-flexible-channel-mapping-try-2 is in progress.  So far what works:

- 4x dropdowns (one per texture channel) in SamplerWidget

    - not too wide (stretches to longest EXR channel name, if that is too wide I can try to learn enough Qt to reduce the size of button to say 3 chars while showing the full width in the popup)

    - hidden for non-EXR

- channels settable in .frag widget specification and/or presets

    - can set fewer than 4 channels, the rest remain unchanged

    - defaults to `R;G;B;A`, if any of these are not present the texture channel defaults to the first EXR channel (eg 4th channel will probably be `B` if there is no `A`)

    - I think defaulting the 4th channel to "one of `A` or `Z` or `DEPTH` or `D`" is too overcomplicated

- loading the requested EXR channels in DisplayWidget works as expected, apart from:

what doesn't work:

- texture cache doesn't yet keep track of EXR channels, so when changing EXR channels you need to either clear the texture cache, or change the texture file to a non-EXR texture, rebuild, change back to EXR texture, rebuild again after setting channels

- this texture cache issue probably breaks loading different sets of channels from the same EXR file into different textures, but taking care of the first issue should fix the second too

**Comment by claudeha** [comment]
I'm stuck on how to redesign the texture cache to support EXR channel lists.

Currently there are a few (conceptual) maps spread around the code that are a bit complicated:

- FragmentSource::textures `: uniformName -> resolvedFileName`
- (via the collection of SamplerWidgets) `: uniformName -> channelList`
- DisplayWidget::textureCache `: resolvedFilename -> openglTextureObject`
- (implicitly in iterator ordering over fs->textures) `: activeUniformName -> openglTextureUnitIndex`
- (implicitly in OpenGL state, set when iterating over fs->textures) `: openglTextureUnitIndex -> openglTextureObject`

The system needs to be upgraded to cache texture image data like `: Pair(resolvedFilename, channelList) -> openglTextureObject` but also needed for setting the OpenGL state is `: uniformName -> openglTextureObject`, which is currently achieved by composing fs->textures with the textureCache but that doesn't take into account the channelList.  Accessing the channel list via the collection of variable widgets is painful.

Any thoughts/recommendations?

**Comment by claudeha** [comment]
I think I figured it out - add the channel list to the TextureCache keys, and add a TextureUnitCache mapping from UniformName to TextureUnit.

**Comment by 3Dickulus** [comment]
Yeah, first off, I screwed something up in the branch merging, sorry bout that...

EXR ... but I wasn't quite finished with this, wanted to finish dynamic names ie: what they are named in the file instead of RGBZ only, (bgrz is just the alpha sorting in the pulldown btw) I think I was about half way into that and that's why they show up but don't load yet.

track used channels as part of settings for a given widget with R;G;B;Z sequence

the checkboxs to allow All or any combination of RGBZ, just had not finished that yet, could probably drop the All entry

the ordering should be the same as in the file and not subject to "juggling" and no matter what the channels are named they will always be var.rgba or var.xyzw GLSL-centric naming

for BGR specifically, the GL texture type needs adjusting, currently GL_RGBA, GL_FLOAT

for me? keeping the code simple is paramount, why code for juggling the input when it ends up as RGBA internally anyways? and GLSL has really good swizzling too so it seems like reinventing the wheel to me. The channels should be loaded in the order they are in the file and use the names from the file so if file is BGRA then that's what you see in the pulldown, any further swizzling is the GLSL coders choice. RGBA or LMNO in exr file is still RGBA for GL

the texture cache should remain as it is, the file is loaded as a texture and the settings for the widget determine the channels to use. different widgets can have the same texture but different channels

don't want to load the same texture multiple times with different channels selected, that's just silly, load it once and use what ever channels you want wherever you want as many times as you want that's what the cache is for . cache = filenameAndTextureID ... settings = channel choice , you don't have to redesign the texture cache to accommodate channels!

compiled from your feature-exr-loader-flexible-channel-mapping-try-2 branch

sorry I couldn't look at this sooner, still groking the sources, the smaller channel boxes are nice...

loading a RGB exr sets the boxes to RGBB, why 4 boxes when only 3 channels?

I will study this over the next few days...

**Comment by 3Dickulus** [comment]
oh, "exr" extension for file dialogs, I have them in all file dialogs but according to the code they shouldn't be there so something is up here, I have OpenEXR stuff installed at the system level for all users, Qt59 loads EXR files and detects OpenEXR libs so adds exr extension to dialogs? not entirely sure but I assumed that other linuxs using Qt59 with OpenEXR installed would behave the same so only added to list if OS = Win where Qt56 is used.

Soon OpenEXR will not be optional but required.

**Comment by claudeha** [comment]
> track used channels as part of settings for a given widget with R;G;B;Z sequence

This works.

> the checkboxs to allow All or any combination of RGBZ, just had not finished that yet, could probably drop the All entry

Check boxes are the wrong UI: can have 0 or more than 4 selected, can't choose order.

> the ordering should be the same as in the file

Why?

> for BGR specifically, the GL texture type needs adjusting, currently GL_RGBA, GL_FLOAT

Don't be so fixated on BGR vs RGB it's all just data. The OpenGL side only has `GL_ RGBA32F` for 4 channels, the naming is historical baggage.

> why code for juggling the input when it ends up as RGBA internally anyways? 

The juggling is necessary to loading support arbitrary channels from EXR files.

> The channels should be loaded in the order they are in the file

Why?

> the texture cache should remain as it is

No, it is broken if you don't add channels to the key.

> the file is loaded as a texture and the settings for the widget determine the channels to use.

No, the widget  channels of the file are loaded into the texture. The texture has 4 channels. The file may have 8 channels. If the cache is from file only, the first widget channels win and the other widgets channels are ignored.

> don't want to load the same texture multiple times with different channels selected, that's just silly

It's necessary, e.g. EXR file has 8 channels and OpenGL texture has 4 channels.

> loading a RGB exr sets the boxes to RGBB, why 4 boxes when only 3 channels?

Simpler code to assume OpenGL texture always has 4 channels.

**Comment by 3Dickulus** [comment]
`mainWindow->getParameter(textureUniformName).split(" ").last().split(";")` gets the currently active channels for a sampler widget as a QStringList, no need for 10 -15 line function when 1 line and a test will do the trick, you're duplicating functionality with getTextureChannels() that already exists as getParameter(varname).

>     the ordering should be the same as in the file
> Why?

because you can order it any way you want in GLSL

>     The channels should be loaded in the order they are in the file
> Why?

consistency ? logic ? so when I'm working in glsl I can be confident that the data is where it should be 0123 = rgba or xyzw... (hyp) ok I loaded my xyzw channels as 3021 uhm ok now translate to glsl wxzy oh wait that's not it it's more like xyzw == wxzy ??? I should leave it alone and just address it as wxzy where needed.

8 channels would be 2 layers of 4 channels?

>     loading a RGB exr sets the boxes to RGBB, why 4 boxes when only 3 channels?
> Simpler code to assume OpenGL texture always has 4 channels.

Simpler to query the file, get channel count and load them up to 4, if more than 4 warn the user that FragM only accepts up to 4 channels, preferably RGBZ, and conversely, fill missing channels with an acceptable default so FragM always has a full texture internally.

the only real functionality for any of this is to load the files that FragM creates, RGBZ, and enable use of them, otherwise saving RGBZ files is pointless. The idea of arbitrary names is fine, that would allow for D or DEPTH as a channel name which some softwares or RGBD cameras might use thereby allowing different scenes to be blended by depth but beyond this is not on the agenda.

it was working nicely (except removing `All` from pulldown) before my branch merging fiasco, I think I kinda shot myself in the foot on that one.

I think pre-juggling channels is great from a twiddler's standpoint but I feel it's not good from a coder's standpoint.

**Comment by 3Dickulus** [comment]
interesting read... https://github.com/OpenImageIO/oiio/issues/1480

got some cool things going re:gl4dev branch
compatibility profile at compile time allows FragM to adapt a bit to fragment requirements

if a frag does not specify a core profile FragM assumes compatibility profile internally so gl_uniforms like gl_ModelViewProjectionMatrix and gl_Vertex are available.

if a frag requests core profile or the OS/Driver says core only then FragM uses no legacy calls internally

uses 2 pixel shaders to render the camera/target paths in core vs compat

...next push to gl4dev branch will have the continuation (fixup for my f*up) of where I was going with EXR channels...

* internal textures are RGBA 4 channels max so truncate and emit warning if more than 4 channels
* TODO: enable a uniformname[0-n] scheme to handle channels > 4 ... layers? 3D textures? if uniformname[n] exists put overflow channels here >>>
* re-sort channels, OpenEXR ALWAYS sorts channel names alphabetically when writing to file, the order we want is rgb[a|z] while the order in the file is [a]bgr[z], only do this if the channels RGB[A|Z] exist in the file otherwise use the names and order from the file.
* accounts for non-existent channels and names them appropriately, if you have RG only it will add empty BA

the channel pulldown has a mutually exclusive scheme where All unchecks the others and any of the others unchecks All. If none are selected you get a valid vec4 texture of 0.0,0.0,0.0,1.0 default is All (or at least should be)

**Comment by 3Dickulus** [comment]
planned for v3 glsl texture 2D arrays for EXR files with more than 4 channels, FragM should warn if uniform is not array and EXR file is > 4 channels, offer code snippet in Edit menu for glsl texture 2D arrays

quote from kronos wiki...

> Array texture sizes are normally limited to the usual GL_MAX_TEXTURE_SIZE limitation. However, the dimension that represents the number of array levels is limited by GL_MAX_ARRAY_TEXTURE_LAYERS, which is generally much smaller. OpenGL 4.5 requires that the limit be at least 2048, while OpenGL 3.0 requires it be at least 256.

**Comment by 3Dickulus** [comment]
studying this a bit more recently... I can not find any examples in VFX pipeline tutorials where pre-swizzling is needed or desired, all expect image data to be presented  as var.rgb and var.rgba and normal or point data to be presented as var.xyz and var.xyzw

I keep coming back to the same place every time I look at this...

FragM should simply load all channels and present them accordingly, image data as var.rgba, norm/point data as var.xyzw and for the case of non-standard channel names they should be presented in the order they are found in the file with a "map key" reported in a message to the log window ie: "Channels L,M,N,O in texture filename map to varname.rgba in GLSL"

the programmer can swizzle them any way they like in GLSL and pre-swizzling will only serve to confuse this process, efforts should be going toward including iSampler, uSampler and other modern widgets instead of bloating the GUI with unnecessary code.

not shutting this down, still looking for a non-hypothetical example....

**Comment by claudeha** [comment]
> for the case of non-standard channel names they should be presented in the order they are found in the file with a "map key" reported in a message to the log window

This would be a usability disaster. Suddenly different files have different appearance just because of an extra channel that isn't even used.

I am still maintaining my feature branch fork because it works well for my use case. Just merged 2.5.1 master.

**Comment by 3Dickulus** [comment]
I don't see a "usability disaster" here...

load RGBA file GLSL sees RGBA pixel layout, if RGB only, A is set to an appropriate default
load XYZW file GLSL sees XYZW data layout, if XYZ only, W is set to an appropriate default
load LMNO file GLSL sees 1234 layout, again empty channels are set to default

I'm reasonably sure that this is the logic that users expect with swizzling done in GLSL code as needed.

as I said "not shutting this down, still looking for a non-hypothetical example...." ( by non-hypothetical I mean workflow scenario that is actually in use, not necessarily common but at least documented)

if it works well for your special use case that's great, love OpenSource.

**Comment by claudeha** [comment]
What should happen when loading `ABGLMNORWXYZ` file? and an `ABGLMNORSTUVWXYZ` file?  What if I want `XY` and `UV` in the same texture (*in that order*, so that `tex.xy` corresponds to `XY` and I don't get horribly confused)?  What if I want `YUVA` (*in that order*, so `tex.a` corresponds to `A`)?

**Comment by 3Dickulus** [comment]
kind of illustrates my point, the only pre-swizzling that should happen is to match channels with known/required layouts in GLSL and if not named as such (order unimportant) they are in alphabetical order.

while digging around the kronos site I find this...

> A vector has up to four components. These can be referred to as (x,y,z,w), (r,g,b,a) or (s,t,p,q). Which naming scheme you use makes no difference; the different schemes are purely for mnemonic value, with xyzw typically used for spatial coordinates, rgba for colours, and stpq for texture coordinates (in the OpenGL API, texture coordinates are referred to as s,t,r,q, but r conflicts with the red component of rgba so GLSL uses p).

...given that then (x,y,z,w), (r,g,b,a) and (s,t,p,q) are the channel names FragM should be aware of and be able to present to the GLSL properly, for additional layouts like rgb[z|d] we can define the transition from alphabetical sorting in EXR files to the required (logical?) order in GLSL with a swizzlemap.

re: Packed YUV formats as in stuff used in linux kernel for hardware by devices like v4l..

- V4L2_PIX_FMT_AYUV32 	‘AYUV’
- V4L2_PIX_FMT_XYUV32 	‘XYUV’
- V4L2_PIX_FMT_VUYA32 	‘VUYA’
- V4L2_PIX_FMT_VUYX32 	‘VUYX’

...these too can be handled internally with a swizzlemap so that at least the order in GLSL is the same as the defined (preferred? expected?) layout.

net result = known pixel layouts are handled in a uniform way

re: ABGLMNORWXYZ wtf???

this would be a candidate for modern GL samplerWidget for textureArray!
3 layers ABGL,MNOR,WXYZ but that's an unlikely case, I've never found a file with more than 4 channels, many layers with 4 channels each but never more than 4 channels. This sort of file would be a specialized case and virtually never encountered by FragM users that just want to put textures into the scene.

A user's preferred channel order for a particular file is entirely up to them in GLSL and it's my feeling that presenting channel swizzling via the current sampler and cubesampler widgets in the gui only serves to confuse users and adds a lot of unnecessary code to maintain. The version that I implemented was working well enough for my needs but I've scrapped it too, because my needs are unique, in favour of something more generic that will, hopefully, cover the majority of use cases.

With FragM being a GLSL development environment I don't want to code things into the GUI that should be done in the GLSL. FragM should only handle getting a texture attached to a sampler in the simplest way... what if you want to port your frag to ShaderToy? If ShaderToy handles ABGLMNORWXYZ files then lets have a look at that code and how often it gets used before attempting it in FragM.

again... not shutting this down, still looking for a real-world example.... or a reason other than "because we can".

p.s. are xyuv unsigned int? uSampler needs to be implemented?

**Comment by 3Dickulus** [comment]
ivec2 uv_coord = ivec2(gl_FragCoord.xy);
float pixel = texelFetch2D(tex, uv_coord,0).x;

...really should implement [i&u]SamplerWidgets for this sort of thing?

**Comment by claudeha** [comment]
https://github.com/claudeha/FragM/tree/develop-feature-exr-channels is current 3Dickulus develop branch merged with my EXR channel stuff.  Here's a quick screenshot with the same file loaded twice with different channel mappings:
![fragm-develop-feature-exr-channels](https://user-images.githubusercontent.com/10728495/87099011-96af7c80-c240-11ea-94e8-2cdf6143670f.png)

**Comment by 3Dickulus** [comment]
very cool, looks good, giving it a study...

**Comment by 3Dickulus** [comment]
observations so far...

1. empty channels get initialized to NaN, in a file with RGB channels only, internally the A( empty 4th ) channel should be initialized to fully opaque. An alpha value of zero represents full transparency, and a value of (2^bitdepth)-1 represents a fully opaque pixel, in png files at least, range for A channel in GL_RGBA32F is 0.0 - 1.0 ? so I think def=NaN should be def=1.0 as that's what is expected in this case. Also the A channel is not exposed, channel boxes only have RGB even though the A channel has been artificially created and inserted.

2. when a sampler is created using an exr file with no default channels specified like... 
`uniform sampler2D tex; file[test-channels.exr]`
...and the file has RGBZ channels the widget always shows the 4th channel as B, should use the channel list from the file as initial default if none are specified?

3. the file dialog button should be a QToolButton (action that opens a window on another thread with it's own event loop) instead of a QPushButton (action within the program window on same thread using program event loop)
also, the file dialog should be wrapped in a test so that cancelling the dialog doesn't alter the current filename in the widget...

VariableWidget.cpp 892 initialize to empty...
`    QString fileName = "";`

VariableWidget.cpp 906 test for cancel!
 change...
```
    dialog.exec();
    fileName = dialog.selectedFiles().at(0);
```
to...
```
    if(dialog.exec() == 1) {
        fileName = dialog.selectedFiles().at(0);
    }
```
...the way it is now if you don't select a file and hit cancel or close the widget is left with a folder path and no filename

still studying and testing as time permits...

**Comment by 3Dickulus** [comment]
Pulled and merged into develop branch, just looking at special cases...
