### ISSUE TITLE
empty `file[]` widget specification no longer works

### ISSUE THREAD

**Issue by claudeha** [3Dickulus/FragM#94]
**Describe the bug**
Previously in FragM this worked:
```
uniform sampler2D Background; file[]
```
Now it fails to build.

**Workaround**
```
uniform sampler2D Background; file[...]
```
and live with the red warning note.

**Expected behavior**
Old frags still work without changes.

**Desktop (please complete the following information):**
 - OS: Debian Buster
 - Gfx card: AMD RX 580
 - Driver version: Vendor: X.Org / Renderer: Radeon RX 580 Series (POLARIS10, DRM 3.27.0, 4.19.0-6-amd64, LLVM 7.0.1) / GL Driver: 4.5 (Compatibility Profile) Mesa 18.3.6

**Additional context**
Library frags may not have a useful default file to load.

**Comment by 3Dickulus** [comment]
It was never supposed to work with an empty file afaik, sampler2D requires a valid file at declaration.

due to adding the channel spec ?

which old frags (in Examples folder) don't work because of this?

**Comment by claudeha** [comment]
don't know about any in existing Examples folder, makes sense to require a file I suppose as samplers need textures? will check what happens if I specify a file that doesn't exist...

**Comment by 3Dickulus** [comment]
from https://stackoverflow.com/questions/42238177/check-if-sampler2d-is-empty
> A sampler cannot be "empty". A valid texture must be bound to the texture units referenced by each sampler in order for rendering to have well-defined behavior.

my experience has been that you get blackness when something is wrong with a sampler in FragM

for a non existent file the log would be something like...
```
Could not resolve path for file: texte2.jpg
Tried path: /Fragmentarium/Examples/Tutorials/texte2.jpg
Tried path: /Fragmentarium/Examples/Include/texte2.jpg
Could not resolve path for file: texte2.jpg
Setting texture to: 
Camera: Click on 2D window for key focus. See Help Menu for more.
Created front and back buffers as RGBA32F
Maximum texture size: 16384x16384
Compiled script in 5 ms.
```

Examples/Tutorials/04-Textures.frag

the shader compiles but doesn't render anything, so, if the declaration is empty or non existent file but the default preset **does** have a valid filename then FragM compiles the shader and sets the sampler properly before the initial render but will issue a red warning line in the log window about the initial declaration having failed to find the file.

I think this behavior is appropriate ???

**Comment by 3Dickulus** [comment]
Note: if the texture file is in the same folder as the user's frag and is in the declaration with no path just the file name FragM will always find it because it checks $FragHome and if that fails it checks Includes folder, also checks the fully specified path if there is one.

Best practice: keep the textures with the frag or if you want global access for all frags put the texture in the Includes folder (which will show in the filename-pulldown for SamplerWidgets)
