### ISSUE TITLE
re: #66

### ISSUE THREAD

**Issue by 3Dickulus** [3Dickulus/FragM#95]
**Description**
Under #66 only the sliders from the main fragment stop the subframe counter while being adjusted while buffershader sliders allow the subframes to keep rendering. When using a heavy frag adjustments take a long time because an accumulation frame is allowed to render for each tick of the mouse poll which continues until maxsubframes is reached.

**To Reproduce**
1. Load a heavy frag
2. drag a main shader slider and observe, subframe rendering stops while adjusting
3. drag a buffer shader slider and observe, subframe rendering continues while adjusting

**Expected behavior**
all sliders stop accumulation while being adjusted
main shader sliders reset accumulation
buffer shader slider allow accumulation to continue

**Desktop**
 - OS: SuSE Linux Leap 15.1
 - Gfx card: nVidia GTX 760
 - Driver version: nVidia 418.87.00

**Comment by claudeha** [comment]
> **To Reproduce**
> Steps to reproduce the behavior:
> 
>     1. Load a heavy frag

I enabled Progressive mode with 0 subframe limit.

>     2. drag a main shader slider and observe, subframe rendering stops while adjusting

Can't reproduce, subframes are still rendered (dragging is laggy) but the count remains at 1 because rendering is reset each time.

>     3. drag a buffer shader slider and observe, subframe rendering continues while adjusting

Yes, same as main shader slider, but count is not reset so the subframe rendering is easier to spot.

**Desktop**

- Debian Buster
- Qt 5.11.3 (afaict)
- AMD RX 580
- Vendor: X.Org / Renderer: Radeon RX 580 Series (POLARIS10, DRM 3.33.0, 5.3.9, LLVM 7.0.1) / GL Driver: 4.5 (Compatibility Profile) Mesa 18.3.6

**Comment by claudeha** [comment]
Oh just saw you made a commit.  Will pull and retest next week when I have time.

**Comment by 3Dickulus** [comment]
yeah, set subframes to 100 or something more than 0, that's a specialized mode for things like the 2D game of life and Reaction Diffusion, this 0 mode is never used for rendering animations to HD... ever, or HiRes images, to get the image accumulating must stop at some point. (it's more of a toy than a tool)

the method I propose here is functionally equivalent to your method but simpler/less code

I think this makes general code maintenance easier, really looking for some feed back from you on this so.... next week then :)

**Comment by claudeha** [comment]
subframes to 0 is just to test the behaviour when dragging

latest Development branch is the same as I reported earlier in this thread
