### ISSUE TITLE
render warning "could not copy ComplexBase.frag"

### ISSUE THREAD

**Issue by claudeha** [3Dickulus/FragM#96]
**Describe the bug**
When rendering a frag with `#version 400 compatibility` and `#include "Complex.frag"`, there is a warning popup saying `ComplexBase.frag` could not be copied.  I think this is because it tries to copy it twice and doesn't want to overwrite it.

**Expected behavior**
The file is copied only once, and no warning popup.

**Desktop (please complete the following information):**
 - OS: Debian Buster

**Additional context**
The dialog must be clicked before rendering starts.

**Comment by 3Dickulus** [comment]
Noted, I think you're right, if there are 2 `#include` statements with the same filename it will try to copy it twice, and it won't overwrite existing frag files when using "Auto Save" in the render dialog. This is so that you can't mixup image/file sets, that's what "Add unique ID to filename" is there for, so your saves are named incrementally. This keeps redundant support files from piling up in the working folder.

Solution: at save time test the set of support file names for the current working frag and discard duplicates before calling saveFile.

afaik Complex.frag is the only case where this will occur :-/

Q: does it create the folder and save the files or is the operation a failure with an incomplete set of files?

**Comment by 3Dickulus** [comment]
Q: can Complex.frag and ComplexBase.frag be reworked so it only needs to include once?

as in : Complex.frag contains ComplexBase.frag code (first) and includes ComplexBase.frag (second)

**Comment by claudeha** [comment]
I don't know if it will be incomplete in general, because in my test 
Complex.frag and thus ComplexBase.frag was the last to be included.

**Comment by claudeha** [comment]
The whole point of the double-include is to avoid the 
otherwise-necessary code duplication.

**Comment by 3Dickulus** [comment]
hm... yes I do recall that...

1. if in list twice then remove one

2. if already saved ( test checksum, timestamp, size or ??? ) don't attempt to save it twice

option 1 would be the easiest

**Comment by 3Dickulus** [comment]
> int QStringList::removeDuplicates()
> This function removes duplicate entries from a list. The entries do not have to be sorted. They will retain their original order.
> 
> Returns the number of removed entries.
> 
> This function was introduced in Qt 4.5.

**Comment by 3Dickulus** [comment]
@ around line 1540? 
```
            if(includeWithAutoSave) {
                // Copy files.
                QStringList ll = p.getDependencies();
                ll.removeDuplicates();                                                 /// add this line
                foreach (QString from, ll) {

```

**Comment by 3Dickulus** [comment]
change
```
Preprocessor::getDependencies() {
        return dependencies;
    }
```
to
```
Preprocessor::getDependencies() {
        dependencies.removeDuplicates();
        return dependencies;
    }
```

**Comment by claudeha** [comment]
> `.removeDuplicates()`

Good solution. Whether to do it each time in `getDependencies()`, once at the end of loading may be better.  But hardly a bottle-neck even if it is quadratic complexity, so whichever is simpler.

**Comment by claudeha** [comment]
BTW I may also want to do a similar double-include thing for quaternion maths.  Won't have time for that for a few more weeks though.

**Comment by 3Dickulus** [comment]
It simply returns 0 if there are no duplicates and in terms of execution time it's only checking a list of 3-5 file names, even at 100 names it's still ridiculously fast

getDependencies() is only called once when "Auto Save Fragments and Settings" is active for a hires tiled render so... no worries, quadratic complexity shouldn't be an issue.
