### ISSUE TITLE
time slider does not update from easing curves in progressive mode

### ISSUE THREAD

**Issue by claudeha** [3Dickulus/FragM#97]
**Describe the bug**
The time slider updates from easing curves in animation mode.  As the time uniform is still updated in progressive mode when the slider is moved, I think it should update from the easing curves too.

**To Reproduce**
1. Add an easing curve to your favourite frag
2. In animation mode, move the time slider: uniforms are updated from easing curve
3. Switch to progressive mode, move the time slider: only the `time` uniform is updated

**Expected behavior**
Time slider updates uniforms from easing curves always. 

**Desktop (please complete the following information):**
 - OS: Debian Buster
 - Gfx card: AMD RX 580

**Additional context**
Workaround of "switch from progressive to animation, touch time slider, switch back to progressive" is tedious.

**Comment by 3Dickulus** [comment]
This has been the case since the start.

Animation features are not active in progressive mode, not keyframes and not easing curves.

Honestly if clicking the mouse twice is just too tedious then I'm not sure what to do about that, these modes are different and serve very different purposes, they should remain de-coupled imho.

Maybe a preferences setting? but it seems like a lot of code to save a mouse click and I think it will only confuse users.

**Comment by 3Dickulus** [comment]
...in this case is it just easing curves to be updated or the animation state that includes key frames ???

**Comment by 3Dickulus** [comment]
Line 2096 in file MainWindow,cpp
`void MainWindow::timeChanged(int value) {...`
replace
`    Q_UNUSED(value)`
with
`        if ( getVariableEditor()->hasEasing() )`
`            engine->updateEasingCurves ( value ); // current frame`

nailed it in two lines :D easy to add a preferences option to enable or disable this

the only thing to do is test this to make sure it doesn't cause problems with creating animations or other render modes and stuff

if all works well maybe can forego other triggering mechanism for easingcurves

**Comment by claudeha** [comment]
> =!

I think you mean `!=`, otherwise subtle bug.

> is it just easing curves to be updated or the animation state that includes key frames 

I'd say it should do everything that dragging the time slider in animation mode does.

Need to check that creating animations is not impeded indeed.  I can try it next week perhaps.

**Comment by 3Dickulus** [comment]
actually that's a human language dyslexism thing =! means: if this = anything but that lol
