### ISSUE TITLE
feature request: add timelime editor to window menu

### ISSUE THREAD

**Issue by claudeha** [3Dickulus/FragM#99]
**Is your feature request related to a problem? Please describe.**
Right-click on time slider to open timeline editor is not discoverable.

**Describe the solution you'd like**
Same behaviour but with an item in the Window menu, so you can find it.

**Describe alternatives you've considered**
Documentation, but who reads that??

**Additional context**
Timeline editor may be useful, but not knowing it is there is a pain.

**Comment by 3Dickulus** [comment]
yes, well it's very beta so only people who take the time to actually read (what little) documentation there is will play with it, not really for public consumption yet, I've done only the most rudimentary testing and haven't looked at it since... back burner for now.
